import { rm } from 'node:fs/promises'
import { fileURLToPath, URL } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import react from '@vitejs/plugin-react'
import { defineConfig, type Plugin } from 'vite'

/**
 * `public/mockServiceWorker.js` is generated by `pnpm exec msw init public --save` so the Vitest browser
 * project can intercept requests at the origin root. It has no business in a deployed bundle, so the
 * production build drops it again.
 */
function dropMockServiceWorker(): Plugin {
  return {
    name: 'shp:drop-mock-service-worker',
    apply: 'build',
    async closeBundle() {
      await rm(fileURLToPath(new URL('./dist/mockServiceWorker.js', import.meta.url)), { force: true })
    },
  }
}

// Frontend architecture: docs/03-architecture/frontend.md. The dev server is reached through Caddy at
// https://app.shp.localhost (and admin.shp.localhost); the API lives on https://api.shp.localhost (ADR-0021).
export default defineConfig({
  plugins: [
    dropMockServiceWorker(),
    tanstackRouter({
      target: 'react',
      autoCodeSplitting: true,
      routesDirectory: './src/routes',
      generatedRouteTree: './src/routeTree.gen.ts',
    }),
    // React Compiler through the Oxc port (experimental in plugin-react 6). Fallback: remove `compiler`.
    react({ compiler: true }),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    host: '0.0.0.0',
    port: 5173,
    strictPort: true,
    allowedHosts: ['app.shp.localhost', 'admin.shp.localhost', 'localhost'],
  },
  build: {
    target: 'es2023',
    sourcemap: true,
  },
})
