/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out and destroy the session */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user, their workspace and permissions */
        get: operations["me.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update interface preferences (theme, density) */
        patch: operations["me.preferences.update"];
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in to a workspace
         * @description The workspace slug selects the tenant; the session then carries it, so no later request
         *     names a tenant. Unknown workspace, unknown email and wrong password answer the same way.
         */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation and set a password */
        post: operations["auth.invitations.accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password-reset link
         * @description Always answers 202, whether or not the address belongs to an account.
         */
        post: operations["auth.password.forgot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset token */
        post: operations["auth.password.reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contacts
         * @description Archived contacts are hidden unless `filter[archived]` is `true` or `all`.
         */
        get: operations["contacts.index"];
        put?: never;
        /** Create a contact */
        post: operations["contacts.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/typeahead": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find contacts as you type
         * @description Fuzzy match on name and email (trigram similarity), best matches first, at most 10.
         */
        get: operations["contacts.typeahead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{contact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show a contact */
        get: operations["contacts.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a contact */
        patch: operations["contacts.update"];
        trace?: never;
    };
    "/contacts/{contact}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a contact. Archived contacts leave the default list but keep their tickets */
        post: operations["contacts.archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{contact}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived contact */
        post: operations["contacts.unarchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organisations */
        get: operations["organizations.index"];
        put?: never;
        /** Create an organisation */
        post: operations["organizations.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organization}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show an organisation */
        get: operations["organizations.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an organisation. Changing the tier affects the priority of new tickets */
        patch: operations["organizations.update"];
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The permission catalogue, grouped by resource */
        get: operations["permissions.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the roles available in this workspace */
        get: operations["roles.index"];
        put?: never;
        /** Create a custom role */
        post: operations["roles.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom role */
        delete: operations["roles.destroy"];
        options?: never;
        head?: never;
        /** Change a custom role's name or permissions */
        patch: operations["roles.update"];
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags, optionally matching a search term (for the tag picker) */
        get: operations["tags.index"];
        put?: never;
        /** Create a tag */
        post: operations["tags.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a tag and remove it from everything it labels */
        delete: operations["tags.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tickets
         * @description Filters combine with AND; comma-separated values within one filter combine with OR.
         *     `search` matches words (full text, stemmed), the ticket number, and short title fragments.
         */
        get: operations["tickets.index"];
        put?: never;
        /**
         * Create a ticket
         * @description The ticket gets the next number of the workspace and starts `open`.
         */
        post: operations["tickets.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show a ticket with its contact, organisation, category and tags */
        get: operations["tickets.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The ticket's history, newest first (cursor pagination) */
        get: operations["tickets.history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the workspace's active categories, in display order. Management arrives in M2-02 */
        get: operations["categories.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Liveness check for clients: answers without authentication and without touching the database.
         */
        get: operations["system.ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitationRequest */
        AcceptInvitationRequest: {
            workspace: string;
            password: string;
            name?: string;
            password_confirmation: string;
        };
        /** CategoryResource */
        CategoryResource: {
            id: string;
            name: string;
            is_active: boolean;
            sort_order: number;
        };
        /**
         * ContactRequest
         * @description Create and update a contact. Email is unique per workspace ignoring case; the organisation must
         *     belong to the same workspace (the tenant scope makes another workspace's id invisible).
         */
        ContactRequest: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string | null;
            /** Format: uuid */
            organization_id?: string | null;
            tags?: string[];
            external_ids?: string[];
            metadata?: string[];
        };
        /** ContactResource */
        ContactResource: {
            id: string;
            name: string;
            email: string;
            phone: string | null;
            organization: {
                id: string;
                name: string;
                tier: components["schemas"]["OrganizationTier"];
            } | null;
            tags: components["schemas"]["TagResource"][];
            external_ids: {
                [key: string]: unknown;
            };
            metadata: {
                [key: string]: unknown;
            };
            last_ticket_at: string | null;
            archived_at: string | null;
            created_at: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            workspace: string;
            /** Format: email */
            email: string;
        };
        /** LoginRequest */
        LoginRequest: {
            workspace: string;
            /** Format: email */
            email: string;
            password: string;
            remember?: boolean;
        };
        /** MeResource */
        MeResource: {
            user: components["schemas"]["UserResource"];
            tenant: components["schemas"]["TenantResource"];
            permissions: string[];
            unread_notifications: number;
        };
        /** OrganizationRequest */
        OrganizationRequest: {
            name: string;
            domain?: string | null;
            tier?: components["schemas"]["OrganizationTier"];
            tags?: string[];
            external_ids?: string[];
            metadata?: string[];
        };
        /** OrganizationResource */
        OrganizationResource: {
            id: string;
            name: string;
            domain: string | null;
            tier: components["schemas"]["OrganizationTier"];
            external_ids: {
                [key: string]: unknown;
            };
            metadata: {
                [key: string]: unknown;
            };
            contacts_count: number;
            tags: components["schemas"]["TagResource"][];
            created_at: string;
        };
        /**
         * OrganizationTier
         * @description Customer tier of an organisation. Feeds the priority customer-tier factor and SLA policy selection; contacts without an organisation count as `standard` (docs/04-domain/contacts.md).
         * @enum {string}
         */
        OrganizationTier: "standard" | "premium" | "enterprise";
        /** PingResource */
        PingResource: {
            /** @constant */
            status: "ok";
        };
        /**
         * Priority
         * @description Ticket priority level. The score behind it comes from the PriorityStrategy (M2-04); a manual override wins over the computed level (docs/04-domain/tickets.md §Fields).
         * @enum {string}
         */
        Priority: "P1" | "P2" | "P3" | "P4";
        /**
         * ProblemDetails
         * @description RFC 9457 problem details.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI of the error page on the docs host.
             */
            type: string;
            /** @description Short, stable summary of the error code. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description User-safe explanation; only for domain, validation, 403 and 419 errors. */
            detail?: string;
            /** @description Stable machine-readable error code (App\Support\Errors\ErrorCode). */
            code: string;
            /** @description Request path. */
            instance: string;
            /** @description Matches the X-Request-Id response header and the log lines. */
            request_id?: string;
            /** @description Validation messages per field (422 only). */
            errors?: {
                [key: string]: string[];
            };
            /** @description Domain-specific context, for example allowed transitions. */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            workspace: string;
            /** Format: email */
            email: string;
            token: string;
            password: string;
            password_confirmation: string;
        };
        /** RoleRequest */
        RoleRequest: {
            name: string;
            permissions: ("tickets.view" | "tickets.create" | "tickets.update" | "tickets.assign" | "tickets.resolve" | "tickets.close" | "tickets.reopen" | "tickets.delete" | "comments.internal" | "contacts.view" | "contacts.manage" | "agents.view" | "agents.manage" | "teams.manage" | "sla.manage" | "calendars.manage" | "shifts.manage" | "media.view" | "media.upload" | "media.manage" | "mail.manage" | "settings.manage" | "users.manage" | "roles.manage" | "integrations.manage" | "reports.view" | "audit.view")[];
        };
        /** RoleResource */
        RoleResource: {
            id: string;
            name: string;
            is_global: boolean;
            is_system: boolean;
            permissions: unknown[];
        };
        /**
         * StoreTicketRequest
         * @description `POST /v1/tickets`. The contact and category must belong to this workspace; the tenant scope
         *     hides every other workspace's rows, so a foreign id fails exactly like an unknown one.
         */
        StoreTicketRequest: {
            title: string;
            description: string;
            /** Format: uuid */
            contact_id: string;
            /** Format: uuid */
            category_id: string;
            impact: number;
            urgency: number;
            tags?: string[];
        };
        /** TagRequest */
        TagRequest: {
            name: string;
            color?: string | null;
        };
        /** TagResource */
        TagResource: {
            id: string;
            name: string;
            slug: string;
            color: string | null;
        };
        /** TenantResource */
        TenantResource: {
            id: string;
            slug: string;
            name: string;
            status: string;
            timezone: string;
        };
        /** TicketEventResource */
        TicketEventResource: {
            id: string;
            type: string;
            actor_type: string;
            actor_id: string | null;
            old_values: {
                [key: string]: unknown;
            };
            new_values: {
                [key: string]: unknown;
            };
            note: string | null;
            created_at: string;
        };
        /** TicketResource */
        TicketResource: {
            id: string;
            number: number;
            title: string;
            description: string;
            status: components["schemas"]["TicketStatus"];
            impact: number;
            urgency: number;
            priority_score: number;
            priority_level: components["schemas"]["Priority"];
            priority_computed_level: components["schemas"]["Priority"];
            priority_overridden: boolean;
            contact_id: string;
            organization_id: string | null;
            category_id: string;
            team_id: string | null;
            assigned_agent_id: string | null;
            duplicate_of_id: string | null;
            created_via: string;
            contact?: {
                id: string;
                name: string;
                email: string;
            };
            organization?: {
                id: string;
                name: string;
                tier: components["schemas"]["OrganizationTier"];
            } | null;
            category?: {
                id: string;
                name: string;
            };
            tags?: components["schemas"]["TagResource"][];
            resolved_at: string | null;
            closed_at: string | null;
            created_at: string;
            updated_at: string;
        };
        /**
         * TicketStatus
         * @description Ticket lifecycle (docs/04-domain/tickets.md §State machine). The transition table lives here and nowhere else; every status change goes through `transitionTo()`.
         * @enum {string}
         */
        TicketStatus: "open" | "assigned" | "in_progress" | "pending" | "resolved" | "closed";
        /** UpdatePreferencesRequest */
        UpdatePreferencesRequest: {
            /** @enum {string} */
            theme?: "light" | "dark" | "system";
            /** @enum {string} */
            density?: "comfortable" | "compact";
        };
        /** UserResource */
        UserResource: {
            id: string;
            name: string;
            email: string;
            is_active: boolean;
            preferences: {
                [key: string]: unknown;
            };
            last_login_at: string | null;
        };
    };
    responses: {
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "me.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `MeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MeResource"];
                    };
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "me.preferences.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequest"];
            };
        };
        responses: {
            /** @description `MeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MeResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description `MeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MeResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "auth.invitations.accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description `MeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MeResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "auth.password.forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @constant */
                            status: "sent";
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "auth.password.reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @constant */
                            status: "reset";
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "contacts.index": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                sort?: string;
                "filter[]"?: string[];
                search?: string | null;
                /** @description Organisation ids, or `none`, comma separated. */
                "filter[organization_id]"?: string;
                /** @description Tag slugs, comma separated. */
                "filter[tag]"?: string;
                /** @description `false` (default), `true` or `all`. */
                "filter[archived]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `ContactResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContactResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "contacts.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description `ContactResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContactResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "contacts.typeahead": {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ContactResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContactResource"][];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "contacts.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The contact ID */
                contact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ContactResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContactResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "contacts.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The contact ID */
                contact: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description `ContactResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContactResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "contacts.archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The contact ID */
                contact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ContactResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContactResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "contacts.unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The contact ID */
                contact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ContactResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContactResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "organizations.index": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                sort?: string;
                "filter[]"?: string[];
                search?: string | null;
                /** @description Tiers, comma separated: standard, premium, enterprise. */
                "filter[tier]"?: string;
                /** @description Tag slugs, comma separated. */
                "filter[tag]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `OrganizationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrganizationResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "organizations.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationRequest"];
            };
        };
        responses: {
            /** @description `OrganizationResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrganizationResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "organizations.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                organization: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `OrganizationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrganizationResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "organizations.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization ID */
                organization: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationRequest"];
            };
        };
        responses: {
            /** @description `OrganizationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OrganizationResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "permissions.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            tickets: [
                                "view",
                                "create",
                                "update",
                                "assign",
                                "resolve",
                                "close",
                                "reopen",
                                "delete"
                            ];
                            comments: [
                                "internal"
                            ];
                            contacts: [
                                "view",
                                "manage"
                            ];
                            agents: [
                                "view",
                                "manage"
                            ];
                            teams: [
                                "manage"
                            ];
                            sla: [
                                "manage"
                            ];
                            calendars: [
                                "manage"
                            ];
                            shifts: [
                                "manage"
                            ];
                            media: [
                                "view",
                                "upload",
                                "manage"
                            ];
                            mail: [
                                "manage"
                            ];
                            settings: [
                                "manage"
                            ];
                            users: [
                                "manage"
                            ];
                            roles: [
                                "manage"
                            ];
                            integrations: [
                                "manage"
                            ];
                            reports: [
                                "view"
                            ];
                            audit: [
                                "view"
                            ];
                        };
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "roles.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `RoleResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleResource"][];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "roles.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description `RoleResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "roles.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The role ID */
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "roles.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The role ID */
                role: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description `RoleResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "tags.index": {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `TagResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TagResource"][];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "tags.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description `TagResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TagResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "tags.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The tag ID */
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "tickets.index": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                sort?: string;
                "filter[]"?: string[];
                search?: string | null;
                include?: string;
                /** @description Statuses, or `active` for everything not resolved or closed. */
                "filter[status]"?: string;
                /** @description Effective levels: P1–P4. */
                "filter[priority]"?: string;
                /** @description Agent ids, or `unassigned`. */
                "filter[assignee_id]"?: string;
                /** @description Team ids, or `none`. */
                "filter[team_id]"?: string;
                /** @description Category ids. */
                "filter[category_id]"?: string;
                /** @description Organisation ids. */
                "filter[organization_id]"?: string;
                /** @description Contact ids. */
                "filter[contact_id]"?: string;
                /** @description Tag slugs. */
                "filter[tag]"?: string;
                /** @description YYYY-MM-DD,YYYY-MM-DD in the workspace time zone, inclusive. */
                "filter[created_between]"?: string;
                /** @description ISO-8601 instant, for pollers. */
                "filter[updated_since]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `TicketResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TicketResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "tickets.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreTicketRequest"];
            };
        };
        responses: {
            /** @description `TicketResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TicketResource"];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "tickets.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ticket ID */
                ticket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `TicketResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TicketResource"] & Record<string, unknown>;
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "tickets.history": {
        parameters: {
            query?: {
                per_page?: number;
                /** @description Opaque cursor from `meta.next_cursor` of the previous page. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description The ticket ID */
                ticket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `TicketEventResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TicketEventResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description The "cursor" that points to the next set of items. */
                            next_cursor: string | null;
                            /** @description The "cursor" that points to the previous set of items. */
                            prev_cursor: string | null;
                        };
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "categories.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `CategoryResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResource"][];
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    "system.ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PingResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PingResource"];
                    };
                };
            };
            /** @description Problem details (RFC 9457) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
