import { setupWorker } from 'msw/browser'
import { afterAll, afterEach, beforeAll } from 'vitest'
import { agentHandlers } from './agents'
import { apiClientHandlers } from './api-clients'
import { contactHandlers } from './contacts'
import { resetMockData } from './data'
import { handlers, TEST_API_ORIGIN } from './handlers'
import { mediaHandlers, TEST_STORAGE_ORIGIN } from './media'
import { notificationHandlers } from './notifications'
import { reportHandlers, resetReportRequests } from './reports'
import { settingsHandlers } from './settings'
import { slaHandlers } from './sla'
import { ticketActivityHandlers } from './ticket-activity'
import { ticketHandlers } from './tickets'
import { userHandlers } from './users'

/**
 * MSW for the Vitest browser project. The service worker in `public/mockServiceWorker.js` (generated by
 * `pnpm exec msw init public --save`) intercepts real `fetch` calls, so components under test go through
 * the same API client as production. Vite's own module and asset loads pass through; a request to the
 * API or storage host that no handler answers is recorded and fails the test that made it, so a missing
 * mock can never reach the real network unnoticed.
 */
export const worker = setupWorker(
  ...handlers,
  ...contactHandlers,
  ...ticketHandlers,
  ...ticketActivityHandlers,
  ...agentHandlers,
  ...slaHandlers,
  ...mediaHandlers,
  ...settingsHandlers,
  ...notificationHandlers,
  ...userHandlers,
  ...apiClientHandlers,
  ...reportHandlers,
)

const unhandled: string[] = []

/** Call at the top of a browser test file. */
export function setupMswWorker(): typeof worker {
  beforeAll(async () => {
    await worker.start({
      quiet: true,
      onUnhandledRequest: (request) => {
        if (request.url.startsWith(TEST_API_ORIGIN) || request.url.startsWith(TEST_STORAGE_ORIGIN))
          unhandled.push(`${request.method} ${request.url}`)
      },
    })
  })
  afterEach(() => {
    worker.resetHandlers()
    resetMockData()
    resetReportRequests()
    const missed = unhandled.splice(0)
    if (missed.length > 0) throw new Error(`Requests without an MSW handler:\n${missed.join('\n')}`)
  })
  afterAll(() => worker.stop())
  return worker
}
