import { setupWorker } from 'msw/browser'
import { afterAll, afterEach, beforeAll } from 'vitest'
import { contactHandlers } from './contacts'
import { resetMockData } from './data'
import { handlers } from './handlers'
import { ticketHandlers } from './tickets'

/**
 * MSW for the Vitest browser project. The service worker in `public/mockServiceWorker.js` (generated by
 * `pnpm exec msw init public --save`) intercepts real `fetch` calls, so components under test go through
 * the same API client as production. Requests we did not mock — Vite's own module and asset loads —
 * pass through.
 */
export const worker = setupWorker(...handlers, ...contactHandlers, ...ticketHandlers)

/** Call at the top of a browser test file. */
export function setupMswWorker(): typeof worker {
  beforeAll(async () => {
    await worker.start({ onUnhandledRequest: 'bypass', quiet: true })
  })
  afterEach(() => {
    worker.resetHandlers()
    resetMockData()
  })
  afterAll(() => worker.stop())
  return worker
}
