/** All user-facing strings live here so a translation layer can replace this module later (docs/03-architecture/frontend.md). */
export const copy = {
  app: {
    name: 'Smart Helpdesk',
    tagline: 'Support tickets with explainable automation.',
    skipToContent: 'Skip to content',
  },
  workspaceEntry: {
    heading: 'Open your workspace',
    body: 'Enter the workspace name your administrator gave you.',
    label: 'Workspace',
    description: 'For example: acme',
    submit: 'Continue',
    required: 'Enter a workspace.',
    invalid: 'A workspace may contain lowercase letters, digits and hyphens only.',
  },
  theme: {
    label: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    /** Announced politely after the user changes the theme. */
    announcement: {
      light: 'Light theme on',
      dark: 'Dark theme on',
      systemLight: 'System theme on, currently light',
      systemDark: 'System theme on, currently dark',
    },
  },
  auth: {
    workspaceLabel: 'Workspace',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    passwordConfirmationLabel: 'Confirm password',
    nameLabel: 'Your name',
    login: {
      heading: 'Sign in',
      body: 'Sign in to the {workspace} workspace.',
      submit: 'Sign in',
      submitting: 'Signing in…',
      forgot: 'Forgot your password?',
      failed: 'Sign-in failed',
      changeWorkspace: 'Use a different workspace',
    },
    acceptInvitation: {
      heading: 'Accept your invitation',
      body: 'Choose a password to finish setting up your account in the {workspace} workspace.',
      submit: 'Create my account',
      submitting: 'Creating your account…',
      missingToken: 'This invitation link is incomplete. Ask your administrator to send a new one.',
      failed: 'The invitation could not be accepted',
      success: 'Your account is ready. You are signed in.',
    },
    forgotPassword: {
      heading: 'Reset your password',
      body: 'We send a reset link to your email address if an account exists in the {workspace} workspace.',
      submit: 'Send the reset link',
      submitting: 'Sending…',
      sent: 'If that address belongs to an account, a reset link is on its way.',
      failed: 'The reset link could not be sent',
      backToLogin: 'Back to sign in',
    },
    resetPassword: {
      heading: 'Choose a new password',
      body: 'Set a new password for your account in the {workspace} workspace.',
      submit: 'Save the new password',
      submitting: 'Saving…',
      failed: 'The password could not be reset',
      success: 'Your password is saved. Sign in with it.',
    },
    signOut: 'Sign out',
    signedOut: 'You are signed out.',
    validation: {
      workspaceRequired: 'Enter a workspace.',
      emailRequired: 'Enter your email address.',
      emailInvalid: 'Enter a valid email address.',
      passwordRequired: 'Enter your password.',
      passwordTooShort: 'Use at least 12 characters.',
      passwordMismatch: 'The two passwords do not match.',
    },
    /** Login failures we explain ourselves; anything else falls back to the problem detail. */
    errors: {
      invalidCredentials: 'The workspace, email or password is incorrect.',
      tenantSuspended: 'This workspace is suspended. Ask your administrator to reactivate it.',
      accountLocked: 'Too many failed attempts. This account is locked for {minutes} minutes.',
      accountLockedNoMinutes: 'Too many failed attempts. This account is locked for a short while.',
      rateLimited: 'Too many attempts. Wait a minute and try again.',
      unexpected: 'Something went wrong. Try again.',
    },
  },
  session: {
    loading: 'Loading your workspace…',
    expired: 'Your session has ended. Sign in again.',
  },
  nav: {
    primary: 'Primary',
    dashboard: 'Dashboard',
    tickets: 'Tickets',
    contacts: 'Contacts',
    organizations: 'Organisations',
    reports: 'Reports',
    settings: 'Settings',
    account: 'Account',
    workspace: 'Workspace',
  },
  shell: {
    breadcrumbs: 'Breadcrumb',
    notifications: {
      label: 'Notifications',
      none: 'No notifications yet.',
      count: '{count} unread notifications',
      announce: '{count} new notifications',
    },
    commandPalette: {
      open: 'Search and commands',
      title: 'Commands',
      description: 'Jump to a page or run a command.',
      placeholder: 'Type a command or page name…',
      navigateGroup: 'Navigate',
      soon: 'Ticket search and actions arrive with the ticket list (roadmap M2-10).',
      close: 'Close',
    },
  },
  dashboard: {
    title: 'Dashboard',
    description: 'Your workspace at a glance.',
    noAccessTitle: 'Reports are not part of your role',
    noAccessBody:
      'The dashboard shows report numbers. Ask a workspace administrator for the reports permission.',
    kpis: 'Key figures',
    charts: 'Charts',
    periodLabel: 'Period',
    openReport: 'Open the full report',
    openReportFor: 'Open the full report: {title}',
    emptyTitle: 'No numbers for this period yet',
    emptyBody: 'Tickets created, resolved and timed in this period appear here.',
    loading: 'Loading the dashboard…',
    loadFailed: 'The dashboard could not be loaded',
  },
  reports: {
    title: 'Reports',
    description: 'Every report of the catalogue you may run, grouped by what it describes.',
    catalogueLabel: 'Report catalogue',
    catalogueEmpty: 'No reports are available to you.',
    catalogueFailed: 'The report catalogue could not be loaded',
    groups: {
      tickets: 'Tickets',
      contacts: 'Contacts and organisations',
      agents: 'Agents and teams',
      sla: 'SLA',
      media: 'Media',
      administration: 'Administration',
    } as Record<string, string>,
    charts: {
      bar: 'Bar chart',
      line: 'Line chart',
      stacked_area: 'Area chart',
      heatmap: 'Heatmap',
      histogram: 'Histogram',
      table: 'Table',
    } as Record<string, string>,
    back: 'All reports',
    loadFailed: 'The report could not be run',
    notFound: 'This report does not exist or is not available to you.',
    parameters: 'Report parameters',
    period: 'Period',
    periods: {
      today: 'Today',
      yesterday: 'Yesterday',
      last_7d: 'Last 7 days',
      last_30d: 'Last 30 days',
      last_90d: 'Last 90 days',
      this_month: 'This month',
      last_month: 'Last month',
      this_year: 'This year',
      custom: 'Custom range',
    } as Record<string, string>,
    customRange: 'Dates',
    compare: 'Compare with the previous period',
    groupBy: 'Group by',
    reset: 'Reset parameters',
    totals: 'Totals',
    chart: 'Chart',
    chartMeasure: 'Chart shows',
    chartDefault: 'Default',
    table: 'Data',
    tableLabel: '{title}: data table',
    showTable: 'Show the data as a table',
    hideTable: 'Hide the table',
    noRows: 'No data for these parameters',
    noRowsBody: 'Try a longer period or remove a filter.',
    truncated: 'Only the first rows are shown; narrow the parameters to see the rest.',
    nowReport: 'This report describes now; the period does not apply.',
    timezone: 'Days are counted in {timezone}.',
    viewRecords: 'View the records behind {value}: {label}, {measure}',
    viewAllRecords: 'View the records of the whole period',
    records: {
      title: 'Records: {label}',
      totalTitle: 'Records of the whole period',
      description: '{total} records behind this number.',
      empty: 'No records behind this number.',
      loadFailed: 'The records could not be loaded',
      close: 'Close',
      label: 'Records',
      previous: 'Previous page',
      next: 'Next page',
      page: 'Page {page} of {pages}',
    },
    print: 'Print',
    drillHint: 'Select a number in the table to see the records behind it.',
    boolean: { any: 'Any', true: 'Yes', false: 'No' },
    /** Option names of the fixed report filters; the same names the API gives the rows. */
    fixedLabels: {
      status: {
        open: 'Open',
        assigned: 'Assigned',
        in_progress: 'In progress',
        pending: 'Pending',
        resolved: 'Resolved',
        closed: 'Closed',
      },
      priority: { P1: 'P1 Critical', P2: 'P2 High', P3: 'P3 Normal', P4: 'P4 Low' },
      channel: { ui: 'Agent (UI)', api: 'API', email: 'Email', seed: 'Seeded' },
      tier: { standard: 'Standard', premium: 'Premium', enterprise: 'Enterprise' },
      age_bucket: {
        '1': 'Under 1 day',
        '2': '1–3 days',
        '3': '3–7 days',
        '4': '7–30 days',
        '5': 'Over 30 days',
      },
      assignment_reason: {
        auto: 'Automatic',
        manual: 'Manual',
        reassign: 'Reassignment',
        unassign: 'Unassignment',
      },
      timer_kind: { first_response: 'First response', resolution: 'Resolution' },
      breach_cause: { first_response: 'No first response in time', resolution: 'Late resolution' },
      duplicate_decision: { pending: 'Pending', accepted: 'Accepted', dismissed: 'Dismissed' },
      actor_type: {
        user: 'User',
        api_client: 'API client',
        system: 'System',
        email: 'Email',
        platform: 'Platform',
      },
      entity_type: {
        sla_policies: 'SLA policies',
        sla_targets: 'SLA targets',
        business_calendars: 'Business calendars',
        calendar_holidays: 'Calendar holidays',
        tenant_settings: 'Workspace settings',
        categories: 'Categories',
        skills: 'Skills',
      },
    } as Record<string, Record<string, string>>,
    none: 'None',
    heatmapLabel: '{title}: heatmap by weekday and hour',
    weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    lessMore: { less: 'Less', more: 'More' },
    change: {
      up: 'Up {change} from {previous}',
      down: 'Down {change} from {previous}',
      flat: 'Unchanged from {previous}',
      none: 'No comparison',
      noneHint: 'Too few records in the previous period to compare.',
      previousPeriod: 'previous period',
    },
    units: {
      seconds: 's',
      minutes: 'm',
      hours: 'h',
      days: 'd',
      percent: '%',
      points: 'pp',
      empty: '—',
      bytes: { bytes: 'bytes', kb: 'KB', mb: 'MB', gb: 'GB' },
    },
  },
  media: {
    title: 'Media library',
    description: 'Files kept in this workspace, including Ticket attachments.',
    folders: 'Folders',
    allFolders: 'All folders',
    noFolder: 'No folder',
    newFolder: 'Folder name',
    createFolder: 'New folder',
    createFolderIn: 'The folder is created inside {name}.',
    createFolderAtRoot: 'The folder is created at the top level. Select a folder first to nest it.',
    renameFolderTitle: 'Rename folder',
    renameFolderBody: 'Give {name} a new name.',
    deleteFolder: 'Delete folder',
    folderCreated: 'Folder created.',
    folderRenamed: 'Folder renamed.',
    tableLabel: 'Media items',
    search: 'Search Media items',
    searchPlaceholder: 'Search by file name…',
    stateFilter: 'Show',
    stateReady: 'Media items',
    stateTrashed: 'Trash',
    emptyTitle: 'No Media items yet',
    emptyBody: 'Upload a file, or attach one to a Ticket, and it appears here.',
    noMatchesTitle: 'No Media items found',
    empty: 'No Media items match this view.',
    used: 'Storage used',
    usedOf: 'Storage used: {used} of {quota}',
    usedCount: '{count} uses',
    none: '—',
    columns: { name: 'Name', size: 'Size', usedIn: 'Used in', createdAt: 'Added', actions: 'Actions' },
    rename: 'Rename',
    move: 'Folder',
    edit: 'Edit',
    editNamed: 'Edit {name}',
    editTitle: 'Edit Media item',
    editDescription: 'Rename the file, move it to another folder or change its tags.',
    save: 'Save',
    saving: 'Saving…',
    saved: 'Media library updated.',
    failed: 'The Media library could not be updated',
    uploaded: 'Media item uploaded.',
    trash: 'Trash',
    trashNamed: 'Move {name} to the trash',
    restore: 'Restore',
    restoreNamed: 'Restore {name}',
    restored: 'Media item restored.',
    purge: 'Purge',
    purgeNamed: 'Purge {name}',
    tags: 'Tags',
    tagFilter: 'Tag',
    confirm: {
      trash: {
        title: 'Move to the trash?',
        body: '{name} leaves the library. It can be restored from the trash until it is purged.',
        action: 'Move to trash',
        done: 'Media item moved to the trash.',
      },
      purge: {
        title: 'Purge this Media item?',
        body: '{name} and its stored file are deleted for good. This cannot be undone.',
        action: 'Purge',
        done: 'Media item purged.',
      },
      folder: {
        title: 'Delete this folder?',
        body: '{name} is deleted. A folder that still holds files or folders cannot be deleted.',
        action: 'Delete folder',
        done: 'Folder deleted.',
      },
    },
    validation: {
      nameRequired: 'Enter a name.',
      folderNameTooLong: 'Use 120 characters or fewer.',
      itemNameTooLong: 'Use 255 characters or fewer.',
      tooManyTags: 'Use 20 tags or fewer.',
    },
    pick: 'Pick from library',
    pickTitle: 'Pick a Media item',
    pickDescription: 'Use a file already stored in this workspace.',
    useItem: 'Use',
    useNamed: 'Use {name}',
    pickedList: 'Files picked from the library',
    unlinkNamed: 'Unlink {name}',
    cancel: 'Cancel',
    selected: 'files selected',
    addFiles: 'Add files',
    uploadHint: 'PNG, JPG, GIF, WebP, PDF, text, CSV, log, Office or ZIP. Up to 25 MB each.',
    uploadFailed: 'The file could not be uploaded.',
    uploadHttpError: 'File storage returned HTTP {status}.',
    uploadNetworkError: 'The upload could not reach file storage.',
    typeNotAllowed: 'This file type is not allowed.',
    sizeNotAllowed: 'Choose a file between 1 byte and 25 MB.',
    ready: 'Ready',
    retry: 'Retry',
    retryFile: 'Retry {name}',
    cancelUpload: 'Cancel upload of {name}',
    removeFile: 'Remove {name}',
    progressLabel: 'Uploading {name}',
    uploadList: 'Files to attach',
    announceReady: '{name} uploaded.',
    announceFailed: '{name} failed: {reason}',
    announceCancelled: 'Upload of {name} cancelled.',
    announceRemoved: '{name} removed.',
    announceLimit: 'Only {max} files can be attached at once.',
    waitForUploads: 'Wait for the uploads to finish, or cancel them.',
    units: { bytes: 'bytes', kb: 'KB', mb: 'MB', gb: 'GB' },
    uploadPermission: 'You do not have permission to upload Media items.',
    noAttachments: 'No attachments yet.',
    unlink: 'Unlink',
    linkFailed: 'The file could not be attached',
    unlinkFailed: 'The file could not be unlinked',
  },
  tickets: {
    title: 'Tickets',
    description: 'Every request in this workspace.',
    detailTitle: 'Ticket',
    list: {
      label: 'Tickets',
      searchLabel: 'Search tickets',
      searchPlaceholder: 'Search words or a ticket number…',
      statusFilter: 'Status',
      priorityFilter: 'Priority',
      categoryFilter: 'Category',
      createdFilter: 'Created',
      assigneeFilter: 'Assignee',
      teamFilter: 'Team',
      tagFilter: 'Tag',
      organizationFilter: 'Organisation',
      slaFilter: 'SLA',
      duplicateFilter: 'Duplicates',
      duplicateAny: 'Any',
      duplicateSuggested: 'Has a duplicate suggestion',
      unassignedOption: 'Unassigned',
      meOption: 'Me',
      noTeamOption: 'No team',
      slaStates: {
        running: 'Running',
        warning: 'Due soon',
        breached: 'Breached',
        paused: 'Paused',
        met: 'Met',
      },
      activeOption: 'Active (not resolved or closed)',
      emptyTitle: 'No tickets yet',
      emptyBody: 'Tickets appear here when contacts write in or when someone creates one.',
      noMatchesTitle: 'No tickets match these filters',
      noMatchesBody: 'Try a shorter search or remove a filter.',
    },
    columns: {
      number: 'Number',
      title: 'Title',
      status: 'Status',
      priority: 'Priority',
      contact: 'Contact',
      category: 'Category',
      createdAt: 'Created',
      updatedAt: 'Updated',
      assignee: 'Assignee',
      team: 'Team',
      slaDue: 'SLA due',
      slaWarning: 'warning',
      slaBreached: 'breached',
      unassigned: 'Unassigned',
      noTeam: 'No team',
      unknownAgent: 'Unknown Agent',
      unknownTeam: 'Unknown Team',
    },
    quickViews: {
      label: 'Quick views',
      all: 'All',
      mine: 'My tickets',
      unassigned: 'Unassigned',
      breaching: 'Breaching soon',
      custom: 'Custom filters',
    },
    bulk: {
      changeStatus: 'Change status',
      assign: 'Assign',
      statusTitle: 'Change status of {count} tickets',
      statusDescription:
        'Each ticket follows the same rules as a single change; tickets that cannot move are listed afterwards.',
      statusLabel: 'New status',
      statusPlaceholder: 'Choose a status',
      statusRequired: 'Choose a status.',
      commentLabel: 'Comment',
      commentOptional: "Optional; added to each ticket's history.",
      commentRequired: 'Explain how the requests were resolved.',
      assignTitle: 'Assign {count} tickets',
      assignDescription: 'Pick an Agent, a Team, or let the assigner choose for each ticket.',
      agentLabel: 'Agent',
      teamLabel: 'Team',
      keepAgent: 'Keep the current Agent',
      keepTeam: 'Keep the current Team',
      autoOption: 'Auto-assign each ticket',
      targetRequired: 'Choose an Agent, a Team or auto-assign.',
      submit: 'Apply to {count} tickets',
      cancel: 'Cancel',
      running: 'Updating {done} of {total} tickets…',
      progress: 'Progress',
      failed: 'The tickets could not be changed',
      resultTitle: 'Bulk change finished',
      resultSummary: '{succeeded} of {total} tickets changed.',
      resultAllOk: 'Every ticket was changed.',
      failuresTitle: 'Not changed ({count})',
      failureRow: '{ticket}: {message}',
      unknownTicket: 'Ticket {id}',
      selectFailed: 'Select failed tickets',
      done: 'Done',
    },
    number: '#{number}',
    status: {
      open: 'Open',
      assigned: 'Assigned',
      in_progress: 'In progress',
      pending: 'Pending',
      resolved: 'Resolved',
      closed: 'Closed',
    },
    priority: {
      P1: 'P1 Critical',
      P2: 'P2 High',
      P3: 'P3 Medium',
      P4: 'P4 Low',
    },
    impact: {
      1: '1 · Single user',
      2: '2 · Team',
      3: '3 · Department',
      4: '4 · Whole organisation',
    },
    urgency: {
      1: '1 · Low',
      2: '2 · Medium',
      3: '3 · High',
      4: '4 · Immediate',
    },
    create: {
      open: 'New ticket',
      title: 'New ticket',
      description:
        'The ticket gets the next number and starts open. Priority follows from impact and urgency.',
      titleLabel: 'Title',
      descriptionLabel: 'Description',
      contactLabel: 'Contact',
      contactPlaceholder: 'Search by name or email…',
      newContact: 'Create a contact',
      loadingContact: 'Loading contact…',
      contactUnavailable: 'The contact details could not be loaded.',
      fullPage: 'Open full create page',
      categoryLabel: 'Category',
      categoryPlaceholder: 'Choose a category',
      impactLabel: 'Impact',
      impactDescription: 'How much of the customer is affected.',
      urgencyLabel: 'Urgency',
      urgencyDescription: 'How quickly harm grows.',
      tagsLabel: 'Tags',
      submit: 'Create ticket',
      submitting: 'Creating…',
      cancel: 'Cancel',
      created: 'Ticket #{number} created.',
      failed: 'The ticket could not be created',
    },
    validation: {
      titleRequired: 'Enter a title.',
      titleTooLong: 'Use at most 200 characters.',
      descriptionRequired: 'Describe the request.',
      contactRequired: 'Choose the contact who asked.',
      categoryRequired: 'Choose a category.',
      levelRequired: 'Choose a level from 1 to 4.',
    },
    detail: {
      back: 'Back to tickets',
      fields: 'Details',
      history: 'History',
      historyEmpty: 'Nothing has happened to this ticket yet.',
      timeline: 'Timeline',
      comments: 'Comments',
      attachments: 'Attachments',
      duplicates: 'Duplicates',
      commentsPending: 'Comments are not available yet.',
      attachmentsPending: 'Attachments are not available yet.',
      duplicatesPending: 'Duplicate suggestions are not available yet.',
      sla: 'SLA',
      slaPending: 'No SLA timers are available for this ticket.',
      team: 'Team',
      agent: 'Agent',
      unassigned: 'Unassigned',
      organizationTier: 'Organisation tier',
      resolvedAt: 'Resolved',
      closedAt: 'Closed',
      loadOlder: 'Load older events',
      loadingOlder: 'Loading older events…',
      tabs: 'Ticket activity',
      edit: 'Edit ticket',
      editDescription: 'Update the request details and priority inputs.',
      save: 'Save changes',
      saving: 'Saving…',
      saved: 'Ticket updated.',
      failed: 'The ticket could not be updated',
      confirm: 'Confirm',
      changing: 'Updating…',
      transitionDescription: 'Confirm this status change for the ticket.',
      resolutionComment: 'Resolution comment',
      resolutionRequired: 'Explain how the request was resolved.',
      pendingWarning: 'Pending means you are waiting on the contact. Send a public reply before waiting.',
      statusChanged: 'Ticket status updated.',
      transitions: {
        open: 'Unassign ticket',
        assigned: 'Assign ticket',
        in_progress: 'Start work',
        pending: 'Set pending',
        resolved: 'Resolve ticket',
        closed: 'Close ticket',
      },
      resume: 'Resume work',
      reopen: 'Reopen ticket',
      whyPriority: 'Why this priority?',
      manual: 'Manual override',
      noExplanation: 'No priority explanation has been recorded yet.',
      strategy: 'Strategy',
      factor: 'Factor',
      value: 'Value',
      weight: 'Weight',
      contribution: 'Contribution',
      score: 'Score {score}',
      createdVia: 'Created via',
      event: '{type} by {actor}',
      system: 'the system',
      user: 'a user',
    },
    duplicates: {
      previewHint: 'Enter a title and description to check for similar tickets.',
      checking: 'Checking for similar tickets…',
      previewFailed: 'Similar tickets could not be checked right now.',
      none: 'No similar tickets found.',
      score: '{score}% similar',
      shared: 'Shared words: {words}',
      decisions: { pending: 'Suggested', accepted: 'Accepted', dismissed: 'Dismissed' },
      mark: 'Mark as duplicate',
      dismiss: 'Dismiss',
      dismissed: 'Suggestion dismissed.',
      marked: 'Ticket marked as duplicate.',
      dismissFailed: 'Suggestion could not be dismissed',
      markFailed: 'Ticket could not be marked as duplicate',
      confirmTitle: 'Mark ticket as duplicate?',
      confirmDescription: 'This closes this ticket and adds an internal note to ticket #{number}.',
    },
  },
  contacts: {
    title: 'Contacts',
    description: 'The people who write to this workspace.',
    newTitle: 'New contact',
    editTitle: 'Contact',
    list: {
      label: 'Contacts',
      searchLabel: 'Search contacts',
      searchPlaceholder: 'Search by name or email…',
      organizationFilter: 'Organisation',
      noOrganizationOption: 'No organisation',
      tagFilter: 'Tag',
      archivedFilter: 'Archived',
      archivedOptions: { false: 'Hide archived', true: 'Only archived', all: 'Include archived' },
      emptyTitle: 'No contacts yet',
      emptyBody: 'Contacts appear here when they write in or when someone adds them.',
      noMatchesTitle: 'No contacts match these filters',
      noMatchesBody: 'Try a shorter search or remove a filter.',
      copyEmails: 'Copy email addresses',
      copiedEmails: 'Copied {count} email addresses.',
      copyFailed: 'The browser did not allow copying. Select the addresses and copy them by hand.',
      create: 'New contact',
      archived: 'Archived',
    },
    columns: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      organization: 'Organisation',
      tags: 'Tags',
      createdAt: 'Added',
      lastTicketAt: 'Last ticket',
    },
    form: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      phoneDescription: 'Optional. Any format your team uses.',
      organization: 'Organisation',
      organizationPlaceholder: 'Search organisations…',
      tags: 'Tags',
      tagsDescription: 'Type to find a tag; a new name creates the tag when you save.',
      create: 'Create contact',
      save: 'Save changes',
      saving: 'Saving…',
      created: '{name} was added.',
      saved: 'Changes saved.',
      failed: 'The contact could not be saved',
    },
    detail: {
      back: 'Back to contacts',
      archive: 'Archive',
      unarchive: 'Restore',
      archived: 'Archived {date}. Archived contacts leave the list but keep their tickets.',
      archivedToast: '{name} was archived.',
      unarchivedToast: '{name} was restored.',
      readOnly: 'You can view this contact; changing it needs the contacts.manage permission.',
    },
    validation: {
      nameRequired: 'Enter a name.',
      nameTooLong: 'Use at most 150 characters.',
      emailRequired: 'Enter an email address.',
      emailInvalid: 'Enter a valid email address.',
      phoneTooLong: 'Use at most 40 characters.',
    },
    none: '—',
  },
  organizations: {
    title: 'Organisations',
    description: 'The companies your contacts belong to.',
    newTitle: 'New organisation',
    editTitle: 'Organisation',
    list: {
      label: 'Organisations',
      searchLabel: 'Search organisations',
      searchPlaceholder: 'Search by name or domain…',
      tierFilter: 'Tier',
      emptyTitle: 'No organisations yet',
      emptyBody: 'Add the companies your contacts work for; their tier feeds ticket priority.',
      noMatchesTitle: 'No organisations match these filters',
      noMatchesBody: 'Try a shorter search or remove a filter.',
      create: 'New organisation',
    },
    columns: {
      name: 'Name',
      domain: 'Domain',
      tier: 'Tier',
      contacts: 'Contacts',
      tags: 'Tags',
      createdAt: 'Added',
    },
    tier: {
      standard: 'Standard',
      premium: 'Premium',
      enterprise: 'Enterprise',
    },
    form: {
      name: 'Name',
      domain: 'Domain',
      domainDescription: 'Optional, for example acme.example.',
      tier: 'Tier',
      tierDescription: 'Feeds the customer-tier factor of ticket priority.',
      tags: 'Tags',
      create: 'Create organisation',
      save: 'Save changes',
      saving: 'Saving…',
      created: '{name} was added.',
      saved: 'Changes saved.',
      failed: 'The organisation could not be saved',
    },
    detail: {
      back: 'Back to organisations',
      readOnly: 'You can view this organisation; changing it needs the contacts.manage permission.',
    },
    validation: {
      nameRequired: 'Enter a name.',
      nameTooLong: 'Use at most 150 characters.',
      domainInvalid: 'Enter a domain such as acme.example, without https://.',
    },
  },
  combobox: {
    noResults: 'No matches',
    loading: 'Searching…',
    clear: 'Clear',
    removeTag: 'Remove {name}',
    addTag: 'Add "{name}"',
  },
  dataTable: {
    loading: 'Loading rows…',
    selectAll: 'Select all rows on this page',
    selectRow: 'Select {label}',
    selectedCount: '{count} selected',
    clearSelection: 'Clear selection',
    bulkActions: 'Actions for the selected rows',
    columns: 'Columns',
    columnsMenu: 'Visible columns',
    rowsPerPage: 'Rows per page',
    range: '{from}–{to} of {total}',
    pageOf: 'Page {page} of {pages}',
    pagination: 'Pagination',
    firstPage: 'First page',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    lastPage: 'Last page',
    keyboardHint: 'Arrow keys move between rows; Enter opens the focused row.',
    pageOutOfRange: {
      title: 'This page is empty',
      body: 'The list is shorter than this page number.',
      action: 'Go to the first page',
    },
  },
  filters: {
    label: 'Filters',
    clear: 'Clear filters',
    searchShortcut: 'Press / to search',
    selectedCount: '{count} selected',
    searchOptions: 'Search {label}',
    noOptions: 'No matches',
    loadingOptions: 'Loading…',
    dateRange: {
      any: 'Any date',
      range: '{from} – {to}',
      clear: 'Clear dates',
      hint: 'Pick the first and the last day.',
    },
  },
  settings: {
    title: 'Settings',
    description: 'Workspace configuration.',
    sections: 'Settings sections',
    directory: 'Directory',
    skills: 'Skills',
    teams: 'Teams',
    categories: 'Categories',
    agents: 'Agents',
    shifts: 'Shifts',
    name: 'Name',
    descriptionLabel: 'Description',
    slug: 'Slug',
    capacity: 'Capacity',
    availability: 'Availability',
    requiredSkills: 'Required skills',
    defaultTeam: 'Default team',
    members: 'Members',
    skillLevel: 'Skill level',
    addSkill: 'Add skill',
    addTeam: 'Add team',
    addCategory: 'Add category',
    addAgent: 'Add agent',
    saveSkill: 'Save skill',
    saveTeam: 'Save team',
    saveCategory: 'Save category',
    saveAgent: 'Save agent',
    saveShifts: 'Save shifts',
    user: 'User',
    day: 'Day',
    date: 'Date',
    startsAt: 'Starts at',
    endsAt: 'Ends at',
    dayOff: 'Day off',
    addShift: 'Add shift',
    addForDay: 'Add {day} shift',
    addException: 'Add date exception',
    weeklyTemplate: 'Weekly template',
    dateExceptions: 'Date exceptions',
    shiftDraft: 'Edit shift rows',
    removeShift: 'Remove shift',
    actions: 'Actions',
    search: 'Search',
    editNamed: 'Edit {name}',
    removeNamed: 'Remove {name}',
    loading: 'Loading…',
    weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    empty: 'No entries yet.',
    select: 'Select an option',
    selectAgent: 'Select an Agent',
    none: 'None',
    saved: 'Changes saved.',
    failed: 'The changes could not be saved.',
    shiftZone: 'Times use the Workspace time zone: {zone}.',
    cancel: 'Cancel',
    saving: 'Saving…',
    userNamed: 'User: {name}',
    dateExceptionOption: 'Date exception',
    shiftRange: '{start}–{end}',
    shiftOff: '{range} · Day off',
    shiftSummary: '{day} · {shift}',
    shiftRow: 'Shift {number}',
    skillLevelNamed: '{skill} · Skill level',
    agentDetails: '{availability} · {open}/{capacity} · {skills}',
    validation: {
      nameRequired: 'Enter a name.',
      nameTooLong60: 'Use 60 characters or fewer.',
      nameTooLong80: 'Use 80 characters or fewer.',
      slugRequired: 'Enter a slug.',
      slugInvalid: 'Use up to 60 lowercase letters and digits, separated by single hyphens.',
      descriptionTooLong: 'Use 1000 characters or fewer.',
      tooMany: 'Choose 50 or fewer.',
      capacity: 'Enter a whole number from 1 to 100.',
      skillLevel: 'Enter a level from 1 to 5.',
      userRequired: 'Choose a user.',
      time: 'Enter a time as HH:MM.',
      shiftDay: 'Choose exactly one weekday or date.',
      shiftDate: 'Choose a date.',
      shiftOrder: 'End time must be after start time.',
    },
    availabilityControl: {
      label: 'Availability',
      available: 'Available',
      away: 'Away',
      offline: 'Offline',
    },
  },
  users: {
    title: 'Users',
    intro:
      'Invite people to this workspace, choose their roles and disable accounts that should no longer sign in.',
    tableLabel: 'Workspace users',
    invite: 'Invite user',
    inviteTitle: 'Invite a user',
    inviteDescription:
      'They get an email with a link that is valid for 48 hours. The roles apply once they accept.',
    sendInvitation: 'Send invitation',
    sending: 'Sending…',
    invited: 'Invitation sent to {email}.',
    editTitle: 'Edit {name}',
    editDescription: 'Change the name and the roles of this user.',
    edit: 'Edit',
    editNamed: 'Edit {name}',
    save: 'Save user',
    saving: 'Saving…',
    saved: 'User saved.',
    cancel: 'Cancel',
    failed: 'The user could not be saved',
    actionFailed: 'The action could not be completed',
    name: 'Name',
    email: 'Email',
    roles: 'Roles',
    rolesHint: 'Roles decide what this user can see and do in the workspace.',
    status: 'Status',
    lastSignIn: 'Last sign-in',
    never: 'Never',
    actions: 'Actions',
    you: 'You',
    search: 'Search users',
    searchPlaceholder: 'Search by name or email',
    statusFilter: 'Status',
    roleFilter: 'Role',
    allRoles: 'All roles',
    statuses: { active: 'Active', invited: 'Invited', disabled: 'Disabled' },
    invitationExpired: 'Invitation expired',
    invitationExpires: 'Invitation valid until {date}',
    resend: 'Resend invitation',
    resendNamed: 'Resend invitation to {name}',
    resent: 'A new invitation was sent to {email}.',
    disable: 'Disable',
    disableNamed: 'Disable {name}',
    enable: 'Enable',
    enableNamed: 'Enable {name}',
    enabled: '{name} can sign in again.',
    disableTitle: 'Disable this user?',
    disableBody: '{name} is signed out and can no longer sign in. You can enable the account again later.',
    disabled: '{name} was disabled.',
    emptyTitle: 'No users yet',
    emptyBody: 'Invite the first colleague to this workspace.',
    noMatchesTitle: 'No users match',
    noMatchesBody: 'Change or clear the filters.',
    forbiddenRoles: '{detail} ({roles})',
    validation: {
      name: 'Enter a name of 2 to 120 characters.',
      email: 'Enter a valid email address.',
      emailLength: 'Use 190 characters or fewer.',
      roles: 'Choose at least one role.',
      rolesMax: 'Choose 10 roles or fewer.',
    },
  },
  roles: {
    title: 'Roles',
    intro:
      'Default roles come with every workspace and cannot be changed. Custom roles combine the permissions you choose.',
    defaults: 'Default roles',
    custom: 'Custom roles',
    customEmpty: 'No custom roles yet.',
    create: 'Create role',
    createTitle: 'Create a custom role',
    editTitle: 'Edit {name}',
    editorDescription:
      'Pick the permissions of this role. You can only add or remove permissions you hold yourself.',
    editNamed: 'Edit {name}',
    deleteNamed: 'Delete {name}',
    save: 'Save role',
    saving: 'Saving…',
    saved: 'Role saved.',
    cancel: 'Cancel',
    failed: 'The role could not be saved',
    name: 'Name',
    nameHint: 'Lowercase letters, digits and hyphens, starting with a letter.',
    permissions: 'Permissions',
    permissionCount: '{count} permissions',
    selectAll: 'All {group} permissions',
    readOnly: 'Read-only',
    deleteTitle: 'Delete this role?',
    deleteBody: 'The custom role {name} is removed from this workspace.',
    deleteAction: 'Delete role',
    deleted: 'Role {name} deleted.',
    deleteFailed: 'The role could not be deleted',
    inUse: '{count} users still hold this role. Give them another role first.',
    inUseOne: '1 user still holds this role. Give them another role first.',
    loadFailed: 'Roles could not be loaded',
    validation: {
      name: 'Use up to 64 lowercase letters, digits and hyphens, starting with a letter.',
      permissions: 'Choose at least one permission.',
    },
    defaultNames: {
      owner: 'Owner',
      admin: 'Admin',
      manager: 'Manager',
      agent: 'Agent',
      developer: 'Developer',
    } as Record<string, string>,
    groups: {
      tickets: 'Tickets',
      comments: 'Comments',
      contacts: 'Contacts',
      agents: 'Agents',
      teams: 'Teams',
      sla: 'SLA',
      calendars: 'Business calendars',
      shifts: 'Shifts',
      media: 'Media',
      mail: 'Mail',
      settings: 'Settings',
      users: 'Users',
      roles: 'Roles',
      integrations: 'Integrations',
      reports: 'Reports',
      audit: 'Audit',
    } as Record<string, string>,
    permissionLabels: {
      'tickets.view': 'View tickets',
      'tickets.create': 'Create tickets',
      'tickets.update': 'Edit tickets',
      'tickets.assign': 'Assign tickets',
      'tickets.resolve': 'Resolve tickets',
      'tickets.close': 'Close tickets',
      'tickets.reopen': 'Reopen tickets',
      'tickets.delete': 'Delete tickets',
      'comments.internal': 'Write internal notes',
      'contacts.view': 'View contacts and organisations',
      'contacts.manage': 'Manage contacts and organisations',
      'agents.view': 'View agents',
      'agents.manage': 'Manage agents',
      'teams.manage': 'Manage teams',
      'sla.manage': 'Manage SLA policies',
      'calendars.manage': 'Manage business calendars',
      'shifts.manage': 'Manage shifts',
      'media.view': 'View media',
      'media.upload': 'Upload media',
      'media.manage': 'Manage media',
      'mail.manage': 'Manage inbound email',
      'settings.manage': 'Manage workspace settings',
      'users.manage': 'Manage users',
      'roles.manage': 'Manage roles',
      'integrations.manage': 'Manage integrations',
      'reports.view': 'View reports',
      'audit.view': 'View the audit log',
    } as Record<string, string>,
  },
  apiClients: {
    nav: 'API clients',
    title: 'API clients',
    intro:
      'Developer access for integrations. A client gets a token from POST /oauth/token with its id and secret (OAuth 2.0 client credentials) and can only use the scopes you give it here.',
    create: 'Create API client',
    createTitle: 'Create an API client',
    createDescription:
      'Name the integration and choose what it may do. Scopes never allow assignment, internal notes or administration.',
    name: 'Name',
    nameHint: 'For example the monitoring tool that will create tickets.',
    scopes: 'Scopes',
    scopesHint: 'The token may carry any of these; request fewer in the token call to narrow it.',
    save: 'Create client',
    saving: 'Creating…',
    cancel: 'Cancel',
    failed: 'The API client could not be created',
    secretTitle: 'Copy the client secret now',
    secretDescription:
      "This is the only time the secret is shown. Store it in your integration's secret store; if it is lost, revoke the client and create a new one.",
    clientId: 'Client id',
    clientSecret: 'Client secret',
    copy: 'Copy',
    copyNamed: 'Copy {name}',
    copied: '{name} copied.',
    copyFailed: 'Copying failed. Select the text and copy it yourself.',
    done: 'I have stored the secret',
    empty: 'No API clients yet.',
    listLabel: 'API clients',
    scopesOf: 'Scopes of {name}',
    columns: {
      name: 'Name',
      scopes: 'Scopes',
      status: 'Status',
      lastUsed: 'Last used',
      created: 'Created',
      actions: 'Actions',
    },
    active: 'Active',
    revoked: 'Revoked',
    never: 'Never',
    revoke: 'Revoke',
    revokeNamed: 'Revoke {name}',
    revokeTitle: 'Revoke this API client?',
    revokeBody:
      '{name} stops working immediately: its tokens are rejected on the next request and it cannot get new ones. This cannot be undone.',
    revokedToast: 'API client {name} revoked.',
    revokeFailed: 'The API client could not be revoked',
    validation: {
      name: 'Enter a name of up to 120 characters.',
      scopes: 'Choose at least one scope.',
    },
  },
  webhooks: {
    nav: 'Webhooks',
    title: 'Webhooks',
    intro:
      'Signed HTTP POSTs to your endpoint when tickets and contacts change. Verify the X-Helpdesk-Signature header with the secret shown when you add the webhook, and reject timestamps older than five minutes.',
    create: 'Add webhook',
    createTitle: 'Add a webhook',
    createDescription: 'The URL must be public https. Choose the events it receives.',
    editTitle: 'Edit {name}',
    editDescription: 'A changed URL is checked again before it is saved.',
    name: 'Name',
    nameHint: 'For example the CRM that mirrors ticket status.',
    url: 'Endpoint URL',
    urlHint: 'https only; private, loopback and cloud-metadata addresses are refused.',
    events: 'Events',
    eventsHint: 'Only these events are sent. Internal notes are never sent.',
    save: 'Add webhook',
    saveChanges: 'Save changes',
    saving: 'Saving…',
    cancel: 'Cancel',
    failed: 'The webhook could not be saved',
    savedToast: 'Webhook {name} saved.',
    secretTitle: 'Copy the signing secret now',
    secretDescription:
      'This is the only time the secret is shown. Store it with your receiver; if it is lost, rotate the secret.',
    rotatedDescription:
      'The previous secret keeps signing for 24 hours (as a second v1= signature), so switch your receiver before then.',
    secret: 'Signing secret',
    done: 'I have stored the secret',
    empty: 'No webhooks yet.',
    listLabel: 'Webhooks',
    eventsOf: 'Events of {name}',
    columns: {
      name: 'Name',
      events: 'Events',
      status: 'Status',
      lastDelivery: 'Last delivery',
      actions: 'Actions',
    },
    active: 'Active',
    disabled: 'Disabled',
    disabledAuto: 'Disabled after repeated failures',
    never: 'Never',
    actionsFor: 'Actions for {name}',
    showDeliveries: 'Deliveries',
    showDeliveriesNamed: 'Show deliveries of {name}',
    edit: 'Edit',
    sendTest: 'Send test',
    testQueued: 'Test delivery queued for {name}.',
    testFailed: 'The test delivery could not be queued.',
    enable: 'Enable',
    disable: 'Disable',
    enabledToast: '{name} enabled.',
    disabledToast: '{name} disabled.',
    toggleFailed: 'The webhook could not be changed.',
    disableTitle: 'Disable this webhook?',
    disableBody: '{name} stops receiving events until you enable it again. Pending retries are dropped.',
    rotate: 'Rotate secret',
    rotateTitle: 'Rotate the signing secret?',
    rotateBody:
      '{name} gets a new secret, shown once. The current secret keeps signing for 24 hours alongside it.',
    rotateFailed: 'The secret could not be rotated',
    delete: 'Delete',
    deleteTitle: 'Delete this webhook?',
    deleteBody: '{name} and its delivery log are deleted. This cannot be undone.',
    deletedToast: 'Webhook {name} deleted.',
    deleteFailed: 'The webhook could not be deleted',
    deliveries: {
      title: 'Deliveries of {name}',
      intro:
        'Newest first. Failed deliveries are retried after 1 min, 5 min, 30 min, 2 h and 12 h, then marked dead.',
      label: 'Deliveries of {name}',
      empty: 'No deliveries yet. Send a test to see one here.',
      loadMore: 'Load older deliveries',
      loadingMore: 'Loading…',
      close: 'Hide deliveries',
      columns: {
        event: 'Event',
        state: 'State',
        attempts: 'Attempts',
        response: 'Response',
        lastAttempt: 'Last attempt',
        nextAttempt: 'Next attempt',
        actions: 'Actions',
      },
      states: {
        pending: 'Pending',
        succeeded: 'Succeeded',
        failed: 'Failed',
        dead: 'Dead',
      },
      noResponse: 'No response',
      retry: 'Retry',
      retryNamed: 'Retry delivery {event}',
      retried: 'Delivery queued again.',
      retryFailed: 'The delivery could not be retried.',
    },
    validation: {
      name: 'Enter a name of up to 80 characters.',
      url: 'Enter a full URL such as https://example.com/hooks/helpdesk.',
      events: 'Choose at least one event.',
    },
  },
  /** Report and ticket-list exports (M3-09): queued files offered through the media library. */
  exports: {
    button: { csv: 'Export CSV', xlsx: 'Export XLSX' } as Record<'csv' | 'xlsx', string>,
    queued: 'Export queued. The file will be ready in a moment.',
    preparing: 'Preparing the export…',
    ready: 'Export ready',
    download: 'Download {name} ({rows} rows)',
    requestFailed: 'The export could not be started.',
    pollFailed: 'The export status could not be loaded.',
    failed: {
      failed: 'The export failed. Try again.',
      too_large: 'The export is larger than 25 MB. Narrow the filters or the period.',
      quota_exceeded: 'The export does not fit in the workspace storage quota.',
      forbidden: 'You can no longer export this.',
    } as Record<string, string>,
  },
  notifications: {
    title: 'Notifications',
    intro:
      'Assignments, replies, SLA warnings and escalations on the tickets you work on, and your finished exports.',
    latest: 'Latest notifications',
    viewAll: 'View all notifications',
    markRead: 'Mark as read',
    markAllRead: 'Mark all as read',
    markReadFailed: 'The notification could not be marked as read.',
    unreadOnly: 'Unread only',
    unread: 'Unread',
    empty: 'You have no notifications.',
    emptyUnread: 'You have read everything.',
    loadFailed: 'Notifications could not be loaded',
    ticket: '#{number} {title}',
    previous: 'Previous page',
    next: 'Next page',
    page: 'Page {page} of {pages}',
    kinds: {
      ticket_assigned: 'A ticket was assigned to you',
      public_reply: 'New public reply on your ticket',
      internal_note: 'New internal note on your ticket',
      sla_warning: 'A ticket is close to its SLA deadline',
      sla_breached: 'A ticket has breached its SLA',
      ticket_escalated: 'The priority of a ticket was raised',
      ticket_unassignable: 'No agent is eligible for a ticket',
      export_ready: 'Your export is ready',
    } as Record<string, string>,
    download: 'Download {name}',
  },
  workspaceSettings: {
    general: 'General',
    branding: 'Branding',
    automation: 'Automation',
    tickets: 'Tickets',
    save: 'Save changes',
    saving: 'Saving…',
    saved: 'Settings saved.',
    failed: 'The settings could not be saved',
    switchFailed: 'The setting could not be changed',
    resetDefaults: 'Reset to defaults',
    generalForm: {
      intro: 'The name and time zone everyone in this workspace sees.',
      name: 'Workspace name',
      timezone: 'Time zone',
      timezoneHelp: 'An IANA time zone such as Asia/Kathmandu. Dates without a zone of their own use it.',
    },
    brandingForm: {
      intro:
        'A primary colour and logos for this workspace. The colour is previewed on this page as you change it.',
      colourLegend: 'Primary colour',
      picker: 'Pick a colour',
      hex: 'Hex colour',
      hexHelp: 'Six hex digits, for example #1d4ed8. Leave empty for the default blue.',
      resetColour: 'Reset to default',
      contrastPass:
        'Text on this colour reaches {ratio}:1 ({foreground} text). Dark theme variant: {dark}:1.',
      contrastFail:
        'Neither light nor dark text reaches 4.5:1 on this colour (best {ratio}:1). Choose a lighter or darker colour.',
      lowOnWhite:
        'This colour has only {ratio}:1 against a white page, so links and focus rings in it are hard to see in the light theme.',
      foregrounds: { '--neutral-0': 'light', '--neutral-950': 'dark' },
      previewLegend: 'Preview',
      previewButton: 'Primary button',
      previewLink: 'A link in the primary colour',
      unsaved: 'Previewing an unsaved colour. It is reverted if you leave without saving.',
      logoLight: 'Logo',
      logoLightHelp: 'Shown in the sidebar in the light theme. PNG, JPEG, GIF or WebP.',
      logoDark: 'Logo for the dark theme',
      logoDarkHelp: 'Optional. Without it the logo is shown on a tile in the dark theme.',
      fileInput: '{label} file',
      upload: 'Upload {label}',
      replace: 'Replace {label}',
      remove: 'Remove {label}',
      uploading: 'Uploading… {progress}%',
      noLogo: 'No logo uploaded.',
      logoAlt: 'Current {label}',
      imagesOnly: 'Choose a PNG, JPEG, GIF or WebP image.',
      uploadFailed: 'The logo could not be uploaded.',
    },
    automationForm: {
      intro: 'What the workspace does on its own when a ticket arrives.',
      assignment: 'Assign new tickets automatically',
      assignmentHelp:
        'A new ticket goes to the eligible agent with the lowest load. Off: tickets wait for a manual assignment.',
      duplicates: 'Duplicate detection',
      threshold: 'Similarity threshold',
      thresholdHelp: 'From 0 to 1. Tickets at least this similar are suggested as duplicates.',
      candidateLimit: 'Tickets compared',
      candidateLimitHelp: 'The most recent tickets compared with a new one (1–200).',
      windowDays: 'Look back (days)',
      windowDaysHelp: 'Only tickets created in this many days are compared (1–365).',
      maxSuggestions: 'Suggestions shown',
      maxSuggestionsHelp: 'At most this many suggestions per ticket (1–20).',
      priorityLink: 'Priority weights and thresholds',
    },
    ticketsForm: {
      intro: 'How long resolved tickets stay open to the contact.',
      autoCloseDays: 'Close resolved tickets after (days)',
      autoCloseDaysHelp:
        'A resolved ticket is closed automatically this many days after it was resolved (1–90).',
      reopenWindowDays: 'Reopen window (days)',
      reopenWindowDaysHelp:
        'A resolved or closed ticket can be reopened for this many days after it was resolved (0–365); 0 means never.',
    },
    slaForm: {
      title: 'SLA defaults',
      warningFraction: 'Warn at this fraction of the target',
      warningFractionHelp:
        'From 0.10 to 0.95. New policies start with it; 0.75 warns when three quarters of the time has passed.',
      firstResponse: 'First response applies to tickets created by agents',
      firstResponseHelp: 'Off: a ticket an agent creates for a contact has no first-response target.',
    },
    shiftsForm: {
      title: 'Shift enforcement',
      enforce: 'Assign only to agents on shift',
      enforceHelp: 'Automatic assignment skips agents whose shift does not cover the current time.',
    },
    validation: {
      nameLength: 'Enter a name of 2 to 80 characters.',
      timezone: 'Enter an IANA time zone such as Asia/Kathmandu.',
      hex: 'Enter a colour as # and six hex digits, for example #1d4ed8.',
      contrast: 'Neither light nor dark text reaches a 4.5:1 contrast on this colour.',
      threshold: 'Enter a number from 0 to 1.',
      candidateLimit: 'Enter a whole number from 1 to 200.',
      windowDays: 'Enter a whole number from 1 to 365.',
      maxSuggestions: 'Enter a whole number from 1 to 20.',
      autoCloseDays: 'Enter a whole number from 1 to 90.',
      reopenWindowDays: 'Enter a whole number from 0 to 365.',
      warningFraction: 'Enter a number from 0.10 to 0.95.',
    },
  },
  sla: {
    policies: 'SLA policies',
    calendars: 'Business calendars',
    addCalendar: 'Add calendar',
    saveCalendar: 'Save calendar',
    noCalendars: 'No Business calendars yet.',
    weeklyHours: 'Weekly working hours',
    timeZone: 'IANA time zone',
    addWindow: 'Add window',
    startsAt: 'Starts at',
    endsAt: 'Ends at',
    holidays: 'Holidays',
    noHolidays: 'No holidays.',
    addHoliday: 'Add holiday',
    saveHoliday: 'Save holiday',
    date: 'Date',
    annual: 'Repeats yearly',
    remove: 'Remove',
    addPolicy: 'Add policy',
    savePolicy: 'Save policy',
    noPolicies: 'No SLA policies yet.',
    tier: 'Organisation tier',
    allTiers: 'Default for all tiers',
    calendar: 'Business calendar',
    alwaysOpen: '24×7',
    warningFraction: 'Warning fraction',
    warningFractionDescription:
      'The share of a target that may pass before the timer warns, for example 0.75.',
    targets: 'Targets by priority',
    minutes: 'minutes',
    default: 'Default',
    edit: 'Edit',
    cancel: 'Cancel',
    firstResponse: 'First response',
    resolution: 'Resolution',
    dueAt: 'Due {time}',
    remainingTime: 'Remaining {time}',
    hoursMinutes: '{hours}h {minutes}m',
    minutesOnly: '{minutes}m',
    strategy: '{name} v{version}',
    timerStates: {
      running: 'Running',
      paused: 'Paused',
      warning: 'Warning',
      breached: 'Breached',
      met: 'Met',
      cancelled: 'Cancelled',
    },
    overdue: 'Overdue',
    paused: 'Paused',
    finished: 'Finished',
    saving: 'Saving…',
    policySaved: 'SLA policy saved.',
    calendarSaved: 'Business calendar saved.',
    holidaySaved: 'Holiday added.',
    holidayRemoved: 'Holiday removed.',
    policyFailed: 'The SLA policy could not be saved',
    calendarFailed: 'The Business calendar could not be saved',
    holidayFailed: 'The holiday could not be saved',
    holidayRemoveFailed: 'The holiday could not be removed',
    removeHolidayTitle: 'Remove this holiday?',
    removeHolidayBody: '{name} on {date} becomes a working day again for SLA timers.',
    removeHolidayNamed: 'Remove {name}',
    editNamed: 'Edit {name}',
    addHolidayTo: 'Add holiday to {name}',
    newPolicy: 'New SLA policy',
    newCalendar: 'New Business calendar',
    policyLine: '{name} · {tier}',
    calendarLine: '{name} · {zone}',
    holidayLine: '{date} · {name}',
    holidayLineAnnual: '{date} · {name} · Repeats yearly',
    targetField: '{priority} {target} (minutes)',
    windowField: '{day} window {number}: {part}',
    addWindowTo: 'Add window to {day}',
    removeWindowFrom: 'Remove {day} window {number}',
    closed: 'Closed',
    tiers: { standard: 'Standard', premium: 'Premium', enterprise: 'Enterprise' },
    days: {
      mon: 'Monday',
      tue: 'Tuesday',
      wed: 'Wednesday',
      thu: 'Thursday',
      fri: 'Friday',
      sat: 'Saturday',
      sun: 'Sunday',
    },
    validation: {
      nameRequired: 'Enter a name.',
      nameTooLong: 'Use 80 characters or fewer.',
      holidayNameTooLong: 'Use 120 characters or fewer.',
      warningFraction: 'Enter a number from 0.10 to 0.95.',
      minutes: 'Enter whole minutes from 1 to 525600.',
      resolutionBeforeResponse: 'Resolution cannot be shorter than the first response.',
      time: 'Enter a time as HH:MM.',
      windowOrder: 'The window must end after it starts.',
      windowOverlap: 'This window overlaps another one on the same day.',
      windowRequired: 'Add at least one working window.',
      timeZone: 'Enter an IANA time zone such as Asia/Kathmandu.',
      date: 'Choose a date.',
    },
  },
  priority: {
    settingsTitle: 'Priority automation',
    intro:
      'How impact, urgency, organisation tier and waiting time become a priority. Preview the worked examples before saving.',
    saveSettings: 'Save priority settings',
    saving: 'Saving…',
    saved: 'Priority settings saved.',
    saveFailed: 'The priority settings could not be saved',
    resetDefaults: 'Reset to defaults',
    weights: 'Weights',
    thresholds: 'Thresholds',
    ageFullHours: 'Age reaches its full weight after (hours)',
    preview: 'Preview scores',
    previewing: 'Scoring…',
    previewFailed: 'The preview could not be computed',
    previewCaption: 'Scores of the worked examples',
    example: 'Example',
    exampleLine: 'Impact {impact}, urgency {urgency}, {tier}, waited {hours} h',
    score: 'Score',
    weightNames: { impact: 'Impact', urgency: 'Urgency', tier: 'Organisation tier', age: 'Age' },
    tiers: { standard: 'Standard', premium: 'Premium', enterprise: 'Enterprise' },
    validation: {
      weight: 'Enter a number from 0 to 1.',
      weightSum: 'The weights must add up to 1.',
      threshold: 'Enter a number from 0 to 100.',
      thresholdOrderP2: 'P2 must be lower than P1.',
      thresholdOrderP3: 'P3 must be lower than P2.',
      ageFullHours: 'Enter a number of hours greater than 0.',
    },
    overrideTitle: 'Override priority',
    overrideDescription: 'Choose a priority manually or return to automatic scoring.',
    overrideSaved: 'Priority updated.',
    level: 'Priority',
    automatic: 'Automatic',
    reason: 'Reason',
    save: 'Save priority',
  },
  assignment: {
    title: 'Assignment',
    description: 'Review eligible Agents and their current load.',
    currentAgent: 'Current Agent',
    currentTeam: 'Team',
    noTeam: 'No Team',
    unknownAgent: 'Unknown Agent',
    unknownTeam: 'Unknown Team',
    assign: 'Assign',
    assignTo: 'Assign to {name}',
    autoAssign: 'Auto-assign',
    unassign: 'Unassign',
    unassigned: 'Ticket unassigned.',
    saved: 'Ticket assigned.',
    failed: 'The assignment could not be changed',
    none: 'No eligible Agents are available.',
    explanationTitle: 'How Agents are ranked',
    explanation:
      'Eligible Agents are ranked by the lowest load (open tickets divided by capacity). When two are equally busy, the one assigned longest ago comes first.',
    strategy: 'Strategy: {name} · {version}',
    rankingCaption: 'Eligible Agents, best first',
    rank: 'Rank',
    agent: 'Agent',
    openTickets: 'Open tickets',
    openOfCapacity: '{open} of {capacity}',
    load: 'Load',
    percent: '{value}%',
    lastAssigned: 'Last assigned',
    neverAssigned: 'Never',
    excluded: 'Excluded Agents ({count})',
    excludedRow: '{name}: {reason}',
    refused: 'Why nobody could take it ({count})',
    missingSkills: 'Missing skills: {skills}',
    reasonUnknown: 'Not eligible',
    reasons: {
      inactive: 'The user account is inactive',
      not_available: 'Not available',
      off_shift: 'Outside their Shift',
      missing_skill: 'Missing a required Skill',
      not_in_team: "Not in the ticket's Team",
      at_capacity: 'At capacity',
    },
  },
  comments: {
    title: 'Ticket comments',
    empty: 'No comments yet.',
    visibility: 'Comment visibility',
    public: 'Public reply',
    internal: 'Internal note',
    body: 'Message',
    publicHint: 'This reply will be emailed to the Contact.',
    internalHint: 'Only Workspace staff can see this note.',
    send: 'Send comment',
    saved: 'Comment added.',
    loadMore: 'Load more comments',
  },
  platform: {
    title: 'Tenants',
    description: 'Every workspace on this installation.',
    heading: 'Platform administration',
    placeholderTitle: 'The platform API arrives in M1-07',
    placeholderBody:
      'This page lists tenants once the platform API and the super-admin guard exist (roadmap M1-07).',
  },
  /** Entity 360 pages: overview and history tabs (roadmap M3-21, docs/04-domain/reporting.md §Entity 360). */
  entity360: {
    tabs: 'Record sections',
    details: 'Details',
    overview: 'Overview',
    history: 'History',
    entities: {
      tickets: 'Ticket',
      contacts: 'Contact',
      organizations: 'Organisation',
      agents: 'Agent',
      teams: 'Team',
      categories: 'Category',
    },
    detailTitles: {
      agents: 'Agent',
      teams: 'Team',
      categories: 'Category',
    },
    backTo: {
      agents: 'All agents',
      teams: 'All teams',
      categories: 'All categories',
    },
    readOnlyDetail: 'Read-only summary. Change this record in Settings.',
    openSettings: 'Open in Settings',
    overviewFailed: 'The overview could not be loaded',
    overviewForbidden: 'Your role does not include the numbers of this record.',
    keyMetrics: 'Key figures',
    last30Days: 'Numbers of the last 30 days.',
    allTime: 'Numbers over every ticket of this record.',
    related: 'Related records',
    trends: 'Trends',
    empty: 'Nothing yet.',
    metrics: {
      first_response_seconds: 'First response (business time)',
      resolution_seconds: 'Resolution (business time)',
      pending_seconds: 'Time pending',
      unassigned_seconds: 'Time unassigned',
      reassignments: 'Reassignments',
      reopens: 'Reopens',
      comments: 'Comments',
      public_replies: 'Public replies',
      first_response_sla: 'First response SLA',
      resolution_sla: 'Resolution SLA',
      tickets: 'Tickets',
      open_tickets: 'Open tickets',
      reopen_rate: 'Reopen rate',
      breached: 'SLA breaches',
      sla_compliance: 'SLA compliance',
      first_response_median_seconds: 'Median first response',
      resolution_median_seconds: 'Median resolution',
      tier: 'Tier',
      contacts: 'Contacts',
      capacity: 'Capacity',
      availability: 'Availability',
      assigned_30d: 'Tickets created (30 days)',
      resolved_30d: 'Resolved (30 days)',
      first_replies_30d: 'First replies (30 days)',
      resolution_median_seconds_30d: 'Median resolution (30 days)',
      sla_compliance_30d: 'SLA compliance (30 days)',
      reopen_rate_30d: 'Reopen rate (30 days)',
    } as Record<string, string>,
    slaOutcome: {
      met: 'Met',
      breached: 'Breached',
      running: 'Running',
      warning: 'Warning',
      paused: 'Paused',
    } as Record<string, string>,
    lifecycle: {
      title: 'Lifecycle trace',
      description: 'Each interval in which status, Agent, Team and priority stayed the same.',
      chartLabel: 'Lifecycle trace: time per interval',
      tableLabel: 'Lifecycle intervals',
      seq: 'Interval',
      status: 'Status',
      agent: 'Agent',
      team: 'Team',
      priority: 'Priority',
      startsAt: 'Starts',
      endsAt: 'Ends',
      wall: 'Wall-clock time',
      business: 'Business time',
      running: 'Still running',
      segment: 'Interval {seq}: {status}, {duration}',
      empty: 'The trace appears once the ticket has been processed.',
    },
    slaTimers: {
      title: 'SLA timers',
      kind: 'Timer',
      cycle: 'Cycle',
      state: 'State',
      dueAt: 'Due',
      metAt: 'Met',
      breachedAt: 'Breached',
      kinds: { first_response: 'First response', resolution: 'Resolution' } as Record<string, string>,
    },
    recentTickets: 'Recent tickets',
    organization: 'Organisation',
    noOrganization: 'No organisation',
    topCategories: 'Top categories',
    tierHistory: 'Tier history',
    tierChange: '{from} → {to}',
    tierFirst: 'Created as {to}',
    skills: 'Skills',
    skillLevel: 'Level {level}',
    teams: 'Teams',
    members: 'Members',
    joined: 'Joined {date}',
    requiredSkills: 'Required skills',
    topAgents: 'Top Agents by resolved tickets',
    columns: {
      number: 'Number',
      title: 'Title',
      status: 'Status',
      createdAt: 'Created',
      name: 'Name',
      tickets: 'Tickets',
      resolved: 'Resolved',
      level: 'Level',
      joinedAt: 'Joined',
    },
    trendTitles: {
      tickets_per_week: 'Tickets per week',
      backlog_per_day: 'Open backlog per day',
    } as Record<string, string>,
    trendDimension: { week: 'Week of', day: 'Day' } as Record<string, string>,
    trendMeasures: { tickets: 'Tickets', backlog: 'Backlog' } as Record<string, string>,
    timeline: {
      title: 'History',
      description: 'Every recorded change, newest first, with who made it.',
      empty: 'No changes have been recorded for this record yet.',
      failed: 'The history could not be loaded',
      forbidden:
        'Your role does not include the history of this record. Ask a workspace administrator for the history permission.',
      loadOlder: 'Load older changes',
      loadingOlder: 'Loading older changes…',
      label: 'Change history',
      operations: {
        insert: 'Created',
        update: 'Changed',
        delete: 'Deleted',
      } as Record<string, string>,
      event: 'Event: {type}',
      by: 'by {actor}',
      from: 'from',
      to: 'to',
      setTo: 'set to',
      cleared: 'cleared',
      updated: 'updated',
      noFields: 'No recorded fields changed.',
      moreFields: '{count} more fields',
      note: 'Note: {note}',
      sources: 'Show',
      sourceAll: 'Changes and events',
      sourceChanges: 'Field changes only',
      sourceEvents: 'Events only',
    },
    actors: {
      you: 'You',
      user: 'User {id}',
      namedUser: '{name}',
      api_client: 'API client {id}',
      system: 'System',
      email: 'Email',
      platform: 'Platform Super Admin',
      unknown: 'Unknown',
    },
    asOf: {
      title: 'As of',
      description:
        'Pick a date and time in {timezone} to see the record as it was then, and what has changed since.',
      label: 'Date and time',
      show: 'Show this state',
      clear: 'Clear',
      useChange: 'See the record just before this change',
      loading: 'Reconstructing…',
      failed: 'The earlier state could not be loaded',
      invalid: 'Enter a date and time.',
      didNotExist: 'This record did not exist on {date}.',
      stateAt: 'State on {date}',
      unchanged: 'Nothing recorded has changed since {date}.',
      versionsAfter: '{count} changes recorded since then.',
      versionsAfterOne: 'One change recorded since then.',
      attribute: 'Field',
      thenLabel: 'Then',
      nowLabel: 'Now',
      differences: 'Differences from now',
      attributes: 'All recorded fields then',
    },
    values: {
      empty: 'Empty',
      yes: 'Yes',
      no: 'No',
      structured: '{count} values',
      shortId: '…{id}',
    },
    /** Readable names of recorded columns; unknown columns fall back to a sentence-cased name. */
    attributes: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      organization_id: 'Organisation',
      external_ids: 'External ids',
      metadata: 'Metadata',
      last_ticket_at: 'Last ticket',
      archived_at: 'Archived',
      created_at: 'Created',
      domain: 'Domain',
      tier: 'Tier',
      number: 'Number',
      title: 'Title',
      description: 'Description',
      contact_id: 'Contact',
      category_id: 'Category',
      team_id: 'Team',
      assigned_agent_id: 'Agent',
      status: 'Status',
      impact: 'Impact',
      urgency: 'Urgency',
      priority_score: 'Priority score',
      priority_level: 'Priority',
      priority_override_level: 'Manual priority',
      priority_override_reason: 'Reason for manual priority',
      priority_override_by: 'Priority set by',
      priority_explanation: 'Priority explanation',
      priority_settings_version: 'Priority settings version',
      duplicate_of_id: 'Duplicate of',
      reopen_count: 'Reopens',
      version: 'Version',
      first_responded_at: 'First response',
      resolved_at: 'Resolved',
      closed_at: 'Closed',
      last_customer_reply_at: 'Last requester reply',
      last_agent_reply_at: 'Last Agent reply',
      pending_since: 'Pending since',
      paused_total_seconds: 'Paused time',
      created_by_user_id: 'Created by',
      created_by_client_id: 'Created by API client',
      created_via: 'Created via',
      user_id: 'User',
      capacity: 'Capacity',
      availability: 'Availability',
      active_ticket_count: 'Open tickets',
      last_assigned_at: 'Last assigned',
      default_team_id: 'Default Team',
      is_active: 'Active',
      sort_order: 'Order',
    } as Record<string, string>,
  },
  states: {
    empty: {
      title: 'Nothing here yet',
    },
    error: {
      title: 'Something went wrong',
      body: 'The request did not finish. Try again, or send the reference below to support.',
      retry: 'Try again',
      requestId: 'Reference {id}',
      offline: 'The server could not be reached. Check your connection and try again.',
    },
    forbidden: {
      title: 'You do not have access to this',
      body: 'Your permissions do not cover this page. Ask a workspace administrator if you need it.',
    },
    notFound: {
      title: 'This page does not exist',
      body: 'The address may be mistyped, or the item was removed.',
      back: 'Back to the dashboard',
    },
  },
  confirm: {
    cancel: 'Cancel',
    failed: 'The action could not be completed',
  },
  /** Our wording for stable problem codes (docs/07-api/errors.md); see `lib/api/problem-messages.ts`. */
  problems: {
    resolutionCommentRequired: 'Add a resolution comment before resolving this ticket.',
    closedAsDuplicate: 'This ticket was closed as a duplicate and cannot be reopened.',
    reopenWindowExpired: 'The reopen window for this ticket has passed. Create a new ticket instead.',
    alreadyDecided: 'Somebody already decided this suggestion. The list was refreshed.',
    alreadyAssigned: 'The ticket was assigned in the meantime. The details were refreshed.',
    noEligibleAgent: 'No Agent is eligible for this ticket. Assign it manually or change the Team.',
    lastOwner: 'This workspace must keep at least one active owner.',
    cannotDisableSelf: 'You cannot disable your own account.',
    bulk: {
      forbidden: 'You are not allowed to change this ticket.',
      notFound: 'This ticket no longer exists.',
      invalidTransition: 'This ticket cannot move to that status from its current one.',
      failed: 'This ticket could not be changed.',
    },
  },
  errors: {
    configMissing: 'The application configuration could not be loaded.',
    notFound: 'This page does not exist.',
  },
} as const

/** Replaces `{name}` placeholders in a copy string. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match))
}
