/** All user-facing strings live here so a translation layer can replace this module later (docs/03-architecture/frontend.md). */
export const copy = {
  app: {
    name: 'Smart Helpdesk',
    tagline: 'Support tickets with explainable automation.',
    skipToContent: 'Skip to content',
  },
  workspaceEntry: {
    heading: 'Open your workspace',
    body: 'Enter the workspace name your administrator gave you.',
    label: 'Workspace',
    description: 'For example: acme',
    submit: 'Continue',
    required: 'Enter a workspace.',
    invalid: 'A workspace may contain lowercase letters, digits and hyphens only.',
  },
  theme: {
    label: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    /** Announced politely after the user changes the theme. */
    announcement: {
      light: 'Light theme on',
      dark: 'Dark theme on',
      systemLight: 'System theme on, currently light',
      systemDark: 'System theme on, currently dark',
    },
  },
  auth: {
    workspaceLabel: 'Workspace',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    passwordConfirmationLabel: 'Confirm password',
    nameLabel: 'Your name',
    login: {
      heading: 'Sign in',
      body: 'Sign in to the {workspace} workspace.',
      submit: 'Sign in',
      submitting: 'Signing in…',
      forgot: 'Forgot your password?',
      failed: 'Sign-in failed',
      changeWorkspace: 'Use a different workspace',
    },
    acceptInvitation: {
      heading: 'Accept your invitation',
      body: 'Choose a password to finish setting up your account in the {workspace} workspace.',
      submit: 'Create my account',
      submitting: 'Creating your account…',
      missingToken: 'This invitation link is incomplete. Ask your administrator to send a new one.',
      failed: 'The invitation could not be accepted',
      success: 'Your account is ready. You are signed in.',
    },
    forgotPassword: {
      heading: 'Reset your password',
      body: 'We send a reset link to your email address if an account exists in the {workspace} workspace.',
      submit: 'Send the reset link',
      submitting: 'Sending…',
      sent: 'If that address belongs to an account, a reset link is on its way.',
      failed: 'The reset link could not be sent',
      backToLogin: 'Back to sign in',
    },
    resetPassword: {
      heading: 'Choose a new password',
      body: 'Set a new password for your account in the {workspace} workspace.',
      submit: 'Save the new password',
      submitting: 'Saving…',
      failed: 'The password could not be reset',
      success: 'Your password is saved. Sign in with it.',
    },
    signOut: 'Sign out',
    signedOut: 'You are signed out.',
    validation: {
      workspaceRequired: 'Enter a workspace.',
      emailRequired: 'Enter your email address.',
      emailInvalid: 'Enter a valid email address.',
      passwordRequired: 'Enter your password.',
      passwordTooShort: 'Use at least 12 characters.',
      passwordMismatch: 'The two passwords do not match.',
    },
    /** Login failures we explain ourselves; anything else falls back to the problem detail. */
    errors: {
      invalidCredentials: 'The workspace, email or password is incorrect.',
      tenantSuspended: 'This workspace is suspended. Ask your administrator to reactivate it.',
      accountLocked: 'Too many failed attempts. This account is locked for {minutes} minutes.',
      accountLockedNoMinutes: 'Too many failed attempts. This account is locked for a short while.',
      rateLimited: 'Too many attempts. Wait a minute and try again.',
      unexpected: 'Something went wrong. Try again.',
    },
  },
  session: {
    loading: 'Loading your workspace…',
    expired: 'Your session has ended. Sign in again.',
  },
  nav: {
    primary: 'Primary',
    dashboard: 'Dashboard',
    tickets: 'Tickets',
    contacts: 'Contacts',
    organizations: 'Organisations',
    settings: 'Settings',
    account: 'Account',
    workspace: 'Workspace',
  },
  shell: {
    breadcrumbs: 'Breadcrumb',
    notifications: {
      label: 'Notifications',
      none: 'No notifications yet.',
      placeholder: 'Notifications arrive with the notification centre (roadmap M2-16).',
      count: '{count} unread notifications',
    },
    commandPalette: {
      open: 'Search and commands',
      title: 'Commands',
      description: 'Jump to a page or run a command.',
      placeholder: 'Type a command or page name…',
      navigateGroup: 'Navigate',
      soon: 'Ticket search and actions arrive with the ticket list (roadmap M2-10).',
      close: 'Close',
    },
  },
  dashboard: {
    title: 'Dashboard',
    description: 'Your workspace at a glance.',
    placeholderTitle: 'The dashboard is on its way',
    placeholderBody: 'Queues, SLA compliance and workload charts arrive with the dashboard (roadmap M3-01).',
  },
  tickets: {
    title: 'Tickets',
    description: 'Every request in this workspace.',
    detailTitle: 'Ticket',
    list: {
      label: 'Tickets',
      searchLabel: 'Search tickets',
      searchPlaceholder: 'Search words or a ticket number…',
      statusFilter: 'Status',
      priorityFilter: 'Priority',
      categoryFilter: 'Category',
      createdFilter: 'Created',
      activeOption: 'Active (not resolved or closed)',
      emptyTitle: 'No tickets yet',
      emptyBody: 'Tickets appear here when contacts write in or when someone creates one.',
      noMatchesTitle: 'No tickets match these filters',
      noMatchesBody: 'Try a shorter search or remove a filter.',
    },
    columns: {
      number: 'Number',
      title: 'Title',
      status: 'Status',
      priority: 'Priority',
      contact: 'Contact',
      category: 'Category',
      createdAt: 'Created',
      updatedAt: 'Updated',
    },
    number: '#{number}',
    status: {
      open: 'Open',
      assigned: 'Assigned',
      in_progress: 'In progress',
      pending: 'Pending',
      resolved: 'Resolved',
      closed: 'Closed',
    },
    priority: {
      P1: 'P1 Critical',
      P2: 'P2 High',
      P3: 'P3 Medium',
      P4: 'P4 Low',
    },
    impact: {
      1: '1 · Single user',
      2: '2 · Team',
      3: '3 · Department',
      4: '4 · Whole organisation',
    },
    urgency: {
      1: '1 · Low',
      2: '2 · Medium',
      3: '3 · High',
      4: '4 · Immediate',
    },
    create: {
      open: 'New ticket',
      title: 'New ticket',
      description:
        'The ticket gets the next number and starts open. Priority follows from impact and urgency.',
      titleLabel: 'Title',
      descriptionLabel: 'Description',
      contactLabel: 'Contact',
      contactPlaceholder: 'Search by name or email…',
      categoryLabel: 'Category',
      categoryPlaceholder: 'Choose a category',
      impactLabel: 'Impact',
      impactDescription: 'How much of the customer is affected.',
      urgencyLabel: 'Urgency',
      urgencyDescription: 'How quickly harm grows.',
      tagsLabel: 'Tags',
      submit: 'Create ticket',
      submitting: 'Creating…',
      cancel: 'Cancel',
      created: 'Ticket #{number} created.',
      failed: 'The ticket could not be created',
    },
    validation: {
      titleRequired: 'Enter a title.',
      titleTooLong: 'Use at most 200 characters.',
      descriptionRequired: 'Describe the request.',
      contactRequired: 'Choose the contact who asked.',
      categoryRequired: 'Choose a category.',
      levelRequired: 'Choose a level from 1 to 4.',
    },
    detail: {
      back: 'Back to tickets',
      fields: 'Details',
      history: 'History',
      historyEmpty: 'Nothing has happened to this ticket yet.',
      placeholder: 'Replies, assignment and status changes arrive with the full ticket page (roadmap M2).',
      score: 'Score {score}',
      createdVia: 'Created via',
      event: '{type} by {actor}',
      system: 'the system',
      user: 'a user',
    },
  },
  contacts: {
    title: 'Contacts',
    description: 'The people who write to this workspace.',
    newTitle: 'New contact',
    editTitle: 'Contact',
    list: {
      label: 'Contacts',
      searchLabel: 'Search contacts',
      searchPlaceholder: 'Search by name or email…',
      organizationFilter: 'Organisation',
      noOrganizationOption: 'No organisation',
      tagFilter: 'Tag',
      archivedFilter: 'Archived',
      archivedOptions: { false: 'Hide archived', true: 'Only archived', all: 'Include archived' },
      emptyTitle: 'No contacts yet',
      emptyBody: 'Contacts appear here when they write in or when someone adds them.',
      noMatchesTitle: 'No contacts match these filters',
      noMatchesBody: 'Try a shorter search or remove a filter.',
      copyEmails: 'Copy email addresses',
      copiedEmails: 'Copied {count} email addresses.',
      copyFailed: 'The browser did not allow copying. Select the addresses and copy them by hand.',
      create: 'New contact',
      archived: 'Archived',
    },
    columns: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      organization: 'Organisation',
      tags: 'Tags',
      createdAt: 'Added',
      lastTicketAt: 'Last ticket',
    },
    form: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      phoneDescription: 'Optional. Any format your team uses.',
      organization: 'Organisation',
      organizationPlaceholder: 'Search organisations…',
      tags: 'Tags',
      tagsDescription: 'Type to find a tag; a new name creates the tag when you save.',
      create: 'Create contact',
      save: 'Save changes',
      saving: 'Saving…',
      created: '{name} was added.',
      saved: 'Changes saved.',
      failed: 'The contact could not be saved',
    },
    detail: {
      back: 'Back to contacts',
      archive: 'Archive',
      unarchive: 'Restore',
      archived: 'Archived {date}. Archived contacts leave the list but keep their tickets.',
      archivedToast: '{name} was archived.',
      unarchivedToast: '{name} was restored.',
      readOnly: 'You can view this contact; changing it needs the contacts.manage permission.',
    },
    validation: {
      nameRequired: 'Enter a name.',
      nameTooLong: 'Use at most 150 characters.',
      emailRequired: 'Enter an email address.',
      emailInvalid: 'Enter a valid email address.',
      phoneTooLong: 'Use at most 40 characters.',
    },
    none: '—',
  },
  organizations: {
    title: 'Organisations',
    description: 'The companies your contacts belong to.',
    newTitle: 'New organisation',
    editTitle: 'Organisation',
    list: {
      label: 'Organisations',
      searchLabel: 'Search organisations',
      searchPlaceholder: 'Search by name or domain…',
      tierFilter: 'Tier',
      emptyTitle: 'No organisations yet',
      emptyBody: 'Add the companies your contacts work for; their tier feeds ticket priority.',
      noMatchesTitle: 'No organisations match these filters',
      noMatchesBody: 'Try a shorter search or remove a filter.',
      create: 'New organisation',
    },
    columns: {
      name: 'Name',
      domain: 'Domain',
      tier: 'Tier',
      contacts: 'Contacts',
      tags: 'Tags',
      createdAt: 'Added',
    },
    tier: {
      standard: 'Standard',
      premium: 'Premium',
      enterprise: 'Enterprise',
    },
    form: {
      name: 'Name',
      domain: 'Domain',
      domainDescription: 'Optional, for example acme.example.',
      tier: 'Tier',
      tierDescription: 'Feeds the customer-tier factor of ticket priority.',
      tags: 'Tags',
      create: 'Create organisation',
      save: 'Save changes',
      saving: 'Saving…',
      created: '{name} was added.',
      saved: 'Changes saved.',
      failed: 'The organisation could not be saved',
    },
    detail: {
      back: 'Back to organisations',
      readOnly: 'You can view this organisation; changing it needs the contacts.manage permission.',
    },
    validation: {
      nameRequired: 'Enter a name.',
      nameTooLong: 'Use at most 150 characters.',
      domainInvalid: 'Enter a domain such as acme.example, without https://.',
    },
  },
  combobox: {
    noResults: 'No matches',
    loading: 'Searching…',
    clear: 'Clear',
    removeTag: 'Remove {name}',
    addTag: 'Add "{name}"',
  },
  dataTable: {
    loading: 'Loading rows…',
    selectAll: 'Select all rows on this page',
    selectRow: 'Select {label}',
    selectedCount: '{count} selected',
    clearSelection: 'Clear selection',
    bulkActions: 'Actions for the selected rows',
    columns: 'Columns',
    columnsMenu: 'Visible columns',
    rowsPerPage: 'Rows per page',
    range: '{from}–{to} of {total}',
    pageOf: 'Page {page} of {pages}',
    pagination: 'Pagination',
    firstPage: 'First page',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    lastPage: 'Last page',
    keyboardHint: 'Arrow keys move between rows; Enter opens the focused row.',
    pageOutOfRange: {
      title: 'This page is empty',
      body: 'The list is shorter than this page number.',
      action: 'Go to the first page',
    },
  },
  filters: {
    label: 'Filters',
    clear: 'Clear filters',
    searchShortcut: 'Press / to search',
    selectedCount: '{count} selected',
    searchOptions: 'Search {label}',
    noOptions: 'No matches',
    loadingOptions: 'Loading…',
    dateRange: {
      any: 'Any date',
      range: '{from} – {to}',
      clear: 'Clear dates',
      hint: 'Pick the first and the last day.',
    },
  },
  settings: {
    title: 'Settings',
    description: 'Workspace configuration.',
    placeholderTitle: 'Settings are on their way',
    placeholderBody: 'General, automation, SLA and developer settings arrive in milestone 2 (roadmap M2-01).',
  },
  platform: {
    title: 'Tenants',
    description: 'Every workspace on this installation.',
    heading: 'Platform administration',
    placeholderTitle: 'The platform API arrives in M1-07',
    placeholderBody:
      'This page lists tenants once the platform API and the super-admin guard exist (roadmap M1-07).',
  },
  states: {
    empty: {
      title: 'Nothing here yet',
    },
    error: {
      title: 'Something went wrong',
      body: 'The request did not finish. Try again, or send the reference below to support.',
      retry: 'Try again',
      requestId: 'Reference {id}',
      offline: 'The server could not be reached. Check your connection and try again.',
    },
    forbidden: {
      title: 'You do not have access to this',
      body: 'Your permissions do not cover this page. Ask a workspace administrator if you need it.',
    },
    notFound: {
      title: 'This page does not exist',
      body: 'The address may be mistyped, or the item was removed.',
      back: 'Back to the dashboard',
    },
  },
  errors: {
    configMissing: 'The application configuration could not be loaded.',
    notFound: 'This page does not exist.',
  },
} as const

/** Replaces `{name}` placeholders in a copy string. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match))
}
