/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/$workspace'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as WorkspaceAppRouteImport } from './routes/$workspace/_app'
import { Route as WorkspaceAuthRouteImport } from './routes/$workspace/_auth'
import { Route as WorkspaceAppIndexRouteImport } from './routes/$workspace/_app/index'
import { Route as WorkspaceAppSettingsRouteImport } from './routes/$workspace/_app/settings'
import { Route as WorkspaceAuthAcceptInvitationRouteImport } from './routes/$workspace/_auth/accept-invitation'
import { Route as WorkspaceAuthLoginRouteImport } from './routes/$workspace/_auth/login'
import { Route as WorkspaceAuthResetPasswordRouteImport } from './routes/$workspace/_auth/reset-password'
import { Route as PlatformPlatformIndexRouteImport } from './routes/_platform.platform.index'
import { Route as PlatformPlatformTenantsRouteImport } from './routes/_platform.platform.tenants'
import { Route as WorkspaceAppContactsIndexRouteImport } from './routes/$workspace/_app/contacts/index'
import { Route as WorkspaceAppContactsContactIdRouteImport } from './routes/$workspace/_app/contacts/$contactId'
import { Route as WorkspaceAppContactsNewRouteImport } from './routes/$workspace/_app/contacts/new'
import { Route as WorkspaceAppOrganizationsIndexRouteImport } from './routes/$workspace/_app/organizations/index'
import { Route as WorkspaceAppOrganizationsOrganizationIdRouteImport } from './routes/$workspace/_app/organizations/$organizationId'
import { Route as WorkspaceAppOrganizationsNewRouteImport } from './routes/$workspace/_app/organizations/new'
import { Route as WorkspaceAppTicketsIndexRouteImport } from './routes/$workspace/_app/tickets/index'
import { Route as WorkspaceAppTicketsTicketIdRouteImport } from './routes/$workspace/_app/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAppRoute = WorkspaceAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAuthRoute = WorkspaceAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAppIndexRoute = WorkspaceAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppSettingsRoute = WorkspaceAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAuthAcceptInvitationRoute =
  WorkspaceAuthAcceptInvitationRouteImport.update({
    id: '/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => WorkspaceAuthRoute,
  } as any)
const WorkspaceAuthLoginRoute = WorkspaceAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WorkspaceAuthRoute,
} as any)
const WorkspaceAuthResetPasswordRoute =
  WorkspaceAuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => WorkspaceAuthRoute,
  } as any)
const PlatformPlatformIndexRoute = PlatformPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPlatformTenantsRoute = PlatformPlatformTenantsRouteImport.update({
  id: '/platform/tenants',
  path: '/platform/tenants',
  getParentRoute: () => PlatformRoute,
} as any)
const WorkspaceAppContactsIndexRoute =
  WorkspaceAppContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppContactsContactIdRoute =
  WorkspaceAppContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppContactsNewRoute = WorkspaceAppContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppOrganizationsIndexRoute =
  WorkspaceAppOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppOrganizationsOrganizationIdRoute =
  WorkspaceAppOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppOrganizationsNewRoute =
  WorkspaceAppOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppTicketsIndexRoute =
  WorkspaceAppTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppTicketsTicketIdRoute =
  WorkspaceAppTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/$workspace/settings': typeof WorkspaceAppSettingsRoute
  '/$workspace/accept-invitation': typeof WorkspaceAuthAcceptInvitationRoute
  '/$workspace/login': typeof WorkspaceAuthLoginRoute
  '/$workspace/reset-password': typeof WorkspaceAuthResetPasswordRoute
  '/platform/tenants': typeof PlatformPlatformTenantsRoute
  '/$workspace/': typeof WorkspaceAppIndexRoute
  '/platform/': typeof PlatformPlatformIndexRoute
  '/$workspace/contacts/$contactId': typeof WorkspaceAppContactsContactIdRoute
  '/$workspace/contacts/new': typeof WorkspaceAppContactsNewRoute
  '/$workspace/organizations/$organizationId': typeof WorkspaceAppOrganizationsOrganizationIdRoute
  '/$workspace/organizations/new': typeof WorkspaceAppOrganizationsNewRoute
  '/$workspace/tickets/$ticketId': typeof WorkspaceAppTicketsTicketIdRoute
  '/$workspace/contacts/': typeof WorkspaceAppContactsIndexRoute
  '/$workspace/organizations/': typeof WorkspaceAppOrganizationsIndexRoute
  '/$workspace/tickets/': typeof WorkspaceAppTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceAppIndexRoute
  '/$workspace/settings': typeof WorkspaceAppSettingsRoute
  '/$workspace/accept-invitation': typeof WorkspaceAuthAcceptInvitationRoute
  '/$workspace/login': typeof WorkspaceAuthLoginRoute
  '/$workspace/reset-password': typeof WorkspaceAuthResetPasswordRoute
  '/platform/tenants': typeof PlatformPlatformTenantsRoute
  '/platform': typeof PlatformPlatformIndexRoute
  '/$workspace/contacts/$contactId': typeof WorkspaceAppContactsContactIdRoute
  '/$workspace/contacts/new': typeof WorkspaceAppContactsNewRoute
  '/$workspace/organizations/$organizationId': typeof WorkspaceAppOrganizationsOrganizationIdRoute
  '/$workspace/organizations/new': typeof WorkspaceAppOrganizationsNewRoute
  '/$workspace/tickets/$ticketId': typeof WorkspaceAppTicketsTicketIdRoute
  '/$workspace/contacts': typeof WorkspaceAppContactsIndexRoute
  '/$workspace/organizations': typeof WorkspaceAppOrganizationsIndexRoute
  '/$workspace/tickets': typeof WorkspaceAppTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/_platform': typeof PlatformRouteWithChildren
  '/$workspace/_app': typeof WorkspaceAppRouteWithChildren
  '/$workspace/_auth': typeof WorkspaceAuthRouteWithChildren
  '/$workspace/_app/settings': typeof WorkspaceAppSettingsRoute
  '/$workspace/_auth/accept-invitation': typeof WorkspaceAuthAcceptInvitationRoute
  '/$workspace/_auth/login': typeof WorkspaceAuthLoginRoute
  '/$workspace/_auth/reset-password': typeof WorkspaceAuthResetPasswordRoute
  '/_platform/platform/tenants': typeof PlatformPlatformTenantsRoute
  '/$workspace/_app/': typeof WorkspaceAppIndexRoute
  '/_platform/platform/': typeof PlatformPlatformIndexRoute
  '/$workspace/_app/contacts/$contactId': typeof WorkspaceAppContactsContactIdRoute
  '/$workspace/_app/contacts/new': typeof WorkspaceAppContactsNewRoute
  '/$workspace/_app/organizations/$organizationId': typeof WorkspaceAppOrganizationsOrganizationIdRoute
  '/$workspace/_app/organizations/new': typeof WorkspaceAppOrganizationsNewRoute
  '/$workspace/_app/tickets/$ticketId': typeof WorkspaceAppTicketsTicketIdRoute
  '/$workspace/_app/contacts/': typeof WorkspaceAppContactsIndexRoute
  '/$workspace/_app/organizations/': typeof WorkspaceAppOrganizationsIndexRoute
  '/$workspace/_app/tickets/': typeof WorkspaceAppTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspace'
    | '/$workspace/settings'
    | '/$workspace/accept-invitation'
    | '/$workspace/login'
    | '/$workspace/reset-password'
    | '/platform/tenants'
    | '/$workspace/'
    | '/platform/'
    | '/$workspace/contacts/$contactId'
    | '/$workspace/contacts/new'
    | '/$workspace/organizations/$organizationId'
    | '/$workspace/organizations/new'
    | '/$workspace/tickets/$ticketId'
    | '/$workspace/contacts/'
    | '/$workspace/organizations/'
    | '/$workspace/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspace'
    | '/$workspace/settings'
    | '/$workspace/accept-invitation'
    | '/$workspace/login'
    | '/$workspace/reset-password'
    | '/platform/tenants'
    | '/platform'
    | '/$workspace/contacts/$contactId'
    | '/$workspace/contacts/new'
    | '/$workspace/organizations/$organizationId'
    | '/$workspace/organizations/new'
    | '/$workspace/tickets/$ticketId'
    | '/$workspace/contacts'
    | '/$workspace/organizations'
    | '/$workspace/tickets'
  id:
    | '__root__'
    | '/'
    | '/$workspace'
    | '/_platform'
    | '/$workspace/_app'
    | '/$workspace/_auth'
    | '/$workspace/_app/settings'
    | '/$workspace/_auth/accept-invitation'
    | '/$workspace/_auth/login'
    | '/$workspace/_auth/reset-password'
    | '/_platform/platform/tenants'
    | '/$workspace/_app/'
    | '/_platform/platform/'
    | '/$workspace/_app/contacts/$contactId'
    | '/$workspace/_app/contacts/new'
    | '/$workspace/_app/organizations/$organizationId'
    | '/$workspace/_app/organizations/new'
    | '/$workspace/_app/tickets/$ticketId'
    | '/$workspace/_app/contacts/'
    | '/$workspace/_app/organizations/'
    | '/$workspace/_app/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace': {
      id: '/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/_app': {
      id: '/$workspace/_app'
      path: ''
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceAppRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/_auth': {
      id: '/$workspace/_auth'
      path: ''
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceAuthRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/_app/': {
      id: '/$workspace/_app/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof WorkspaceAppIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/settings': {
      id: '/$workspace/_app/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof WorkspaceAppSettingsRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_auth/accept-invitation': {
      id: '/$workspace/_auth/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/$workspace/accept-invitation'
      preLoaderRoute: typeof WorkspaceAuthAcceptInvitationRouteImport
      parentRoute: typeof WorkspaceAuthRoute
    }
    '/$workspace/_auth/login': {
      id: '/$workspace/_auth/login'
      path: '/login'
      fullPath: '/$workspace/login'
      preLoaderRoute: typeof WorkspaceAuthLoginRouteImport
      parentRoute: typeof WorkspaceAuthRoute
    }
    '/$workspace/_auth/reset-password': {
      id: '/$workspace/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/$workspace/reset-password'
      preLoaderRoute: typeof WorkspaceAuthResetPasswordRouteImport
      parentRoute: typeof WorkspaceAuthRoute
    }
    '/_platform/platform/': {
      id: '/_platform/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformPlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/platform/tenants': {
      id: '/_platform/platform/tenants'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformPlatformTenantsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/$workspace/_app/contacts/': {
      id: '/$workspace/_app/contacts/'
      path: '/contacts'
      fullPath: '/$workspace/contacts/'
      preLoaderRoute: typeof WorkspaceAppContactsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/contacts/$contactId': {
      id: '/$workspace/_app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/$workspace/contacts/$contactId'
      preLoaderRoute: typeof WorkspaceAppContactsContactIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/contacts/new': {
      id: '/$workspace/_app/contacts/new'
      path: '/contacts/new'
      fullPath: '/$workspace/contacts/new'
      preLoaderRoute: typeof WorkspaceAppContactsNewRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/organizations/': {
      id: '/$workspace/_app/organizations/'
      path: '/organizations'
      fullPath: '/$workspace/organizations/'
      preLoaderRoute: typeof WorkspaceAppOrganizationsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/organizations/$organizationId': {
      id: '/$workspace/_app/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/$workspace/organizations/$organizationId'
      preLoaderRoute: typeof WorkspaceAppOrganizationsOrganizationIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/organizations/new': {
      id: '/$workspace/_app/organizations/new'
      path: '/organizations/new'
      fullPath: '/$workspace/organizations/new'
      preLoaderRoute: typeof WorkspaceAppOrganizationsNewRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/tickets/': {
      id: '/$workspace/_app/tickets/'
      path: '/tickets'
      fullPath: '/$workspace/tickets/'
      preLoaderRoute: typeof WorkspaceAppTicketsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/tickets/$ticketId': {
      id: '/$workspace/_app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/$workspace/tickets/$ticketId'
      preLoaderRoute: typeof WorkspaceAppTicketsTicketIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
  }
}

interface WorkspaceAppRouteChildren {
  WorkspaceAppSettingsRoute: typeof WorkspaceAppSettingsRoute
  WorkspaceAppIndexRoute: typeof WorkspaceAppIndexRoute
  WorkspaceAppContactsContactIdRoute: typeof WorkspaceAppContactsContactIdRoute
  WorkspaceAppContactsNewRoute: typeof WorkspaceAppContactsNewRoute
  WorkspaceAppOrganizationsOrganizationIdRoute: typeof WorkspaceAppOrganizationsOrganizationIdRoute
  WorkspaceAppOrganizationsNewRoute: typeof WorkspaceAppOrganizationsNewRoute
  WorkspaceAppTicketsTicketIdRoute: typeof WorkspaceAppTicketsTicketIdRoute
  WorkspaceAppContactsIndexRoute: typeof WorkspaceAppContactsIndexRoute
  WorkspaceAppOrganizationsIndexRoute: typeof WorkspaceAppOrganizationsIndexRoute
  WorkspaceAppTicketsIndexRoute: typeof WorkspaceAppTicketsIndexRoute
}

const WorkspaceAppRouteChildren: WorkspaceAppRouteChildren = {
  WorkspaceAppSettingsRoute: WorkspaceAppSettingsRoute,
  WorkspaceAppIndexRoute: WorkspaceAppIndexRoute,
  WorkspaceAppContactsContactIdRoute: WorkspaceAppContactsContactIdRoute,
  WorkspaceAppContactsNewRoute: WorkspaceAppContactsNewRoute,
  WorkspaceAppOrganizationsOrganizationIdRoute:
    WorkspaceAppOrganizationsOrganizationIdRoute,
  WorkspaceAppOrganizationsNewRoute: WorkspaceAppOrganizationsNewRoute,
  WorkspaceAppTicketsTicketIdRoute: WorkspaceAppTicketsTicketIdRoute,
  WorkspaceAppContactsIndexRoute: WorkspaceAppContactsIndexRoute,
  WorkspaceAppOrganizationsIndexRoute: WorkspaceAppOrganizationsIndexRoute,
  WorkspaceAppTicketsIndexRoute: WorkspaceAppTicketsIndexRoute,
}

const WorkspaceAppRouteWithChildren = WorkspaceAppRoute._addFileChildren(
  WorkspaceAppRouteChildren,
)

interface WorkspaceAuthRouteChildren {
  WorkspaceAuthAcceptInvitationRoute: typeof WorkspaceAuthAcceptInvitationRoute
  WorkspaceAuthLoginRoute: typeof WorkspaceAuthLoginRoute
  WorkspaceAuthResetPasswordRoute: typeof WorkspaceAuthResetPasswordRoute
}

const WorkspaceAuthRouteChildren: WorkspaceAuthRouteChildren = {
  WorkspaceAuthAcceptInvitationRoute: WorkspaceAuthAcceptInvitationRoute,
  WorkspaceAuthLoginRoute: WorkspaceAuthLoginRoute,
  WorkspaceAuthResetPasswordRoute: WorkspaceAuthResetPasswordRoute,
}

const WorkspaceAuthRouteWithChildren = WorkspaceAuthRoute._addFileChildren(
  WorkspaceAuthRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceAppRoute: typeof WorkspaceAppRouteWithChildren
  WorkspaceAuthRoute: typeof WorkspaceAuthRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAppRoute: WorkspaceAppRouteWithChildren,
  WorkspaceAuthRoute: WorkspaceAuthRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface PlatformRouteChildren {
  PlatformPlatformTenantsRoute: typeof PlatformPlatformTenantsRoute
  PlatformPlatformIndexRoute: typeof PlatformPlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformPlatformTenantsRoute: PlatformPlatformTenantsRoute,
  PlatformPlatformIndexRoute: PlatformPlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
