/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/$workspace'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as WorkspaceAppRouteImport } from './routes/$workspace/_app'
import { Route as WorkspaceAuthRouteImport } from './routes/$workspace/_auth'
import { Route as WorkspaceAppIndexRouteImport } from './routes/$workspace/_app/index'
import { Route as WorkspaceAppNotificationsRouteImport } from './routes/$workspace/_app/notifications'
import { Route as WorkspaceAppSettingsRouteImport } from './routes/$workspace/_app/settings'
import { Route as WorkspaceAuthAcceptInvitationRouteImport } from './routes/$workspace/_auth/accept-invitation'
import { Route as WorkspaceAuthLoginRouteImport } from './routes/$workspace/_auth/login'
import { Route as WorkspaceAuthResetPasswordRouteImport } from './routes/$workspace/_auth/reset-password'
import { Route as PlatformPlatformIndexRouteImport } from './routes/_platform.platform.index'
import { Route as PlatformPlatformTenantsRouteImport } from './routes/_platform.platform.tenants'
import { Route as WorkspaceAppContactsIndexRouteImport } from './routes/$workspace/_app/contacts/index'
import { Route as WorkspaceAppContactsContactIdRouteImport } from './routes/$workspace/_app/contacts/$contactId'
import { Route as WorkspaceAppContactsNewRouteImport } from './routes/$workspace/_app/contacts/new'
import { Route as WorkspaceAppOrganizationsIndexRouteImport } from './routes/$workspace/_app/organizations/index'
import { Route as WorkspaceAppOrganizationsOrganizationIdRouteImport } from './routes/$workspace/_app/organizations/$organizationId'
import { Route as WorkspaceAppOrganizationsNewRouteImport } from './routes/$workspace/_app/organizations/new'
import { Route as WorkspaceAppReportsIndexRouteImport } from './routes/$workspace/_app/reports/index'
import { Route as WorkspaceAppReportsReportKeyRouteImport } from './routes/$workspace/_app/reports/$reportKey'
import { Route as WorkspaceAppSettingsIndexRouteImport } from './routes/$workspace/_app/settings/index'
import { Route as WorkspaceAppSettingsAgentsRouteImport } from './routes/$workspace/_app/settings/agents'
import { Route as WorkspaceAppSettingsApiClientsRouteImport } from './routes/$workspace/_app/settings/api-clients'
import { Route as WorkspaceAppSettingsAutomationRouteImport } from './routes/$workspace/_app/settings/automation'
import { Route as WorkspaceAppSettingsBrandingRouteImport } from './routes/$workspace/_app/settings/branding'
import { Route as WorkspaceAppSettingsCalendarsRouteImport } from './routes/$workspace/_app/settings/calendars'
import { Route as WorkspaceAppSettingsCategoriesRouteImport } from './routes/$workspace/_app/settings/categories'
import { Route as WorkspaceAppSettingsGeneralRouteImport } from './routes/$workspace/_app/settings/general'
import { Route as WorkspaceAppSettingsMediaRouteImport } from './routes/$workspace/_app/settings/media'
import { Route as WorkspaceAppSettingsPriorityRouteImport } from './routes/$workspace/_app/settings/priority'
import { Route as WorkspaceAppSettingsRolesRouteImport } from './routes/$workspace/_app/settings/roles'
import { Route as WorkspaceAppSettingsShiftsRouteImport } from './routes/$workspace/_app/settings/shifts'
import { Route as WorkspaceAppSettingsSkillsRouteImport } from './routes/$workspace/_app/settings/skills'
import { Route as WorkspaceAppSettingsSlaRouteImport } from './routes/$workspace/_app/settings/sla'
import { Route as WorkspaceAppSettingsTeamsRouteImport } from './routes/$workspace/_app/settings/teams'
import { Route as WorkspaceAppSettingsTicketsRouteImport } from './routes/$workspace/_app/settings/tickets'
import { Route as WorkspaceAppSettingsUsersRouteImport } from './routes/$workspace/_app/settings/users'
import { Route as WorkspaceAppTicketsIndexRouteImport } from './routes/$workspace/_app/tickets/index'
import { Route as WorkspaceAppTicketsTicketIdRouteImport } from './routes/$workspace/_app/tickets/$ticketId'
import { Route as WorkspaceAppTicketsNewRouteImport } from './routes/$workspace/_app/tickets/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAppRoute = WorkspaceAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAuthRoute = WorkspaceAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAppIndexRoute = WorkspaceAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppNotificationsRoute =
  WorkspaceAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppSettingsRoute = WorkspaceAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAuthAcceptInvitationRoute =
  WorkspaceAuthAcceptInvitationRouteImport.update({
    id: '/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => WorkspaceAuthRoute,
  } as any)
const WorkspaceAuthLoginRoute = WorkspaceAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WorkspaceAuthRoute,
} as any)
const WorkspaceAuthResetPasswordRoute =
  WorkspaceAuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => WorkspaceAuthRoute,
  } as any)
const PlatformPlatformIndexRoute = PlatformPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPlatformTenantsRoute = PlatformPlatformTenantsRouteImport.update({
  id: '/platform/tenants',
  path: '/platform/tenants',
  getParentRoute: () => PlatformRoute,
} as any)
const WorkspaceAppContactsIndexRoute =
  WorkspaceAppContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppContactsContactIdRoute =
  WorkspaceAppContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppContactsNewRoute = WorkspaceAppContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => WorkspaceAppRoute,
} as any)
const WorkspaceAppOrganizationsIndexRoute =
  WorkspaceAppOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppOrganizationsOrganizationIdRoute =
  WorkspaceAppOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppOrganizationsNewRoute =
  WorkspaceAppOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppReportsIndexRoute =
  WorkspaceAppReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppReportsReportKeyRoute =
  WorkspaceAppReportsReportKeyRouteImport.update({
    id: '/reports/$reportKey',
    path: '/reports/$reportKey',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppSettingsIndexRoute =
  WorkspaceAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsAgentsRoute =
  WorkspaceAppSettingsAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsApiClientsRoute =
  WorkspaceAppSettingsApiClientsRouteImport.update({
    id: '/api-clients',
    path: '/api-clients',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsAutomationRoute =
  WorkspaceAppSettingsAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsBrandingRoute =
  WorkspaceAppSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsCalendarsRoute =
  WorkspaceAppSettingsCalendarsRouteImport.update({
    id: '/calendars',
    path: '/calendars',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsCategoriesRoute =
  WorkspaceAppSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsGeneralRoute =
  WorkspaceAppSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsMediaRoute =
  WorkspaceAppSettingsMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsPriorityRoute =
  WorkspaceAppSettingsPriorityRouteImport.update({
    id: '/priority',
    path: '/priority',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsRolesRoute =
  WorkspaceAppSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsShiftsRoute =
  WorkspaceAppSettingsShiftsRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsSkillsRoute =
  WorkspaceAppSettingsSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsSlaRoute = WorkspaceAppSettingsSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => WorkspaceAppSettingsRoute,
} as any)
const WorkspaceAppSettingsTeamsRoute =
  WorkspaceAppSettingsTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsTicketsRoute =
  WorkspaceAppSettingsTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppSettingsUsersRoute =
  WorkspaceAppSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => WorkspaceAppSettingsRoute,
  } as any)
const WorkspaceAppTicketsIndexRoute =
  WorkspaceAppTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppTicketsTicketIdRoute =
  WorkspaceAppTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => WorkspaceAppRoute,
  } as any)
const WorkspaceAppTicketsNewRoute = WorkspaceAppTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => WorkspaceAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/$workspace/notifications': typeof WorkspaceAppNotificationsRoute
  '/$workspace/settings': typeof WorkspaceAppSettingsRouteWithChildren
  '/$workspace/accept-invitation': typeof WorkspaceAuthAcceptInvitationRoute
  '/$workspace/login': typeof WorkspaceAuthLoginRoute
  '/$workspace/reset-password': typeof WorkspaceAuthResetPasswordRoute
  '/platform/tenants': typeof PlatformPlatformTenantsRoute
  '/$workspace/': typeof WorkspaceAppIndexRoute
  '/platform/': typeof PlatformPlatformIndexRoute
  '/$workspace/contacts/$contactId': typeof WorkspaceAppContactsContactIdRoute
  '/$workspace/contacts/new': typeof WorkspaceAppContactsNewRoute
  '/$workspace/organizations/$organizationId': typeof WorkspaceAppOrganizationsOrganizationIdRoute
  '/$workspace/organizations/new': typeof WorkspaceAppOrganizationsNewRoute
  '/$workspace/reports/$reportKey': typeof WorkspaceAppReportsReportKeyRoute
  '/$workspace/settings/agents': typeof WorkspaceAppSettingsAgentsRoute
  '/$workspace/settings/api-clients': typeof WorkspaceAppSettingsApiClientsRoute
  '/$workspace/settings/automation': typeof WorkspaceAppSettingsAutomationRoute
  '/$workspace/settings/branding': typeof WorkspaceAppSettingsBrandingRoute
  '/$workspace/settings/calendars': typeof WorkspaceAppSettingsCalendarsRoute
  '/$workspace/settings/categories': typeof WorkspaceAppSettingsCategoriesRoute
  '/$workspace/settings/general': typeof WorkspaceAppSettingsGeneralRoute
  '/$workspace/settings/media': typeof WorkspaceAppSettingsMediaRoute
  '/$workspace/settings/priority': typeof WorkspaceAppSettingsPriorityRoute
  '/$workspace/settings/roles': typeof WorkspaceAppSettingsRolesRoute
  '/$workspace/settings/shifts': typeof WorkspaceAppSettingsShiftsRoute
  '/$workspace/settings/skills': typeof WorkspaceAppSettingsSkillsRoute
  '/$workspace/settings/sla': typeof WorkspaceAppSettingsSlaRoute
  '/$workspace/settings/teams': typeof WorkspaceAppSettingsTeamsRoute
  '/$workspace/settings/tickets': typeof WorkspaceAppSettingsTicketsRoute
  '/$workspace/settings/users': typeof WorkspaceAppSettingsUsersRoute
  '/$workspace/tickets/$ticketId': typeof WorkspaceAppTicketsTicketIdRoute
  '/$workspace/tickets/new': typeof WorkspaceAppTicketsNewRoute
  '/$workspace/contacts/': typeof WorkspaceAppContactsIndexRoute
  '/$workspace/organizations/': typeof WorkspaceAppOrganizationsIndexRoute
  '/$workspace/reports/': typeof WorkspaceAppReportsIndexRoute
  '/$workspace/settings/': typeof WorkspaceAppSettingsIndexRoute
  '/$workspace/tickets/': typeof WorkspaceAppTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceAppIndexRoute
  '/$workspace/notifications': typeof WorkspaceAppNotificationsRoute
  '/$workspace/accept-invitation': typeof WorkspaceAuthAcceptInvitationRoute
  '/$workspace/login': typeof WorkspaceAuthLoginRoute
  '/$workspace/reset-password': typeof WorkspaceAuthResetPasswordRoute
  '/platform/tenants': typeof PlatformPlatformTenantsRoute
  '/platform': typeof PlatformPlatformIndexRoute
  '/$workspace/contacts/$contactId': typeof WorkspaceAppContactsContactIdRoute
  '/$workspace/contacts/new': typeof WorkspaceAppContactsNewRoute
  '/$workspace/organizations/$organizationId': typeof WorkspaceAppOrganizationsOrganizationIdRoute
  '/$workspace/organizations/new': typeof WorkspaceAppOrganizationsNewRoute
  '/$workspace/reports/$reportKey': typeof WorkspaceAppReportsReportKeyRoute
  '/$workspace/settings/agents': typeof WorkspaceAppSettingsAgentsRoute
  '/$workspace/settings/api-clients': typeof WorkspaceAppSettingsApiClientsRoute
  '/$workspace/settings/automation': typeof WorkspaceAppSettingsAutomationRoute
  '/$workspace/settings/branding': typeof WorkspaceAppSettingsBrandingRoute
  '/$workspace/settings/calendars': typeof WorkspaceAppSettingsCalendarsRoute
  '/$workspace/settings/categories': typeof WorkspaceAppSettingsCategoriesRoute
  '/$workspace/settings/general': typeof WorkspaceAppSettingsGeneralRoute
  '/$workspace/settings/media': typeof WorkspaceAppSettingsMediaRoute
  '/$workspace/settings/priority': typeof WorkspaceAppSettingsPriorityRoute
  '/$workspace/settings/roles': typeof WorkspaceAppSettingsRolesRoute
  '/$workspace/settings/shifts': typeof WorkspaceAppSettingsShiftsRoute
  '/$workspace/settings/skills': typeof WorkspaceAppSettingsSkillsRoute
  '/$workspace/settings/sla': typeof WorkspaceAppSettingsSlaRoute
  '/$workspace/settings/teams': typeof WorkspaceAppSettingsTeamsRoute
  '/$workspace/settings/tickets': typeof WorkspaceAppSettingsTicketsRoute
  '/$workspace/settings/users': typeof WorkspaceAppSettingsUsersRoute
  '/$workspace/tickets/$ticketId': typeof WorkspaceAppTicketsTicketIdRoute
  '/$workspace/tickets/new': typeof WorkspaceAppTicketsNewRoute
  '/$workspace/contacts': typeof WorkspaceAppContactsIndexRoute
  '/$workspace/organizations': typeof WorkspaceAppOrganizationsIndexRoute
  '/$workspace/reports': typeof WorkspaceAppReportsIndexRoute
  '/$workspace/settings': typeof WorkspaceAppSettingsIndexRoute
  '/$workspace/tickets': typeof WorkspaceAppTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/_platform': typeof PlatformRouteWithChildren
  '/$workspace/_app': typeof WorkspaceAppRouteWithChildren
  '/$workspace/_auth': typeof WorkspaceAuthRouteWithChildren
  '/$workspace/_app/notifications': typeof WorkspaceAppNotificationsRoute
  '/$workspace/_app/settings': typeof WorkspaceAppSettingsRouteWithChildren
  '/$workspace/_auth/accept-invitation': typeof WorkspaceAuthAcceptInvitationRoute
  '/$workspace/_auth/login': typeof WorkspaceAuthLoginRoute
  '/$workspace/_auth/reset-password': typeof WorkspaceAuthResetPasswordRoute
  '/_platform/platform/tenants': typeof PlatformPlatformTenantsRoute
  '/$workspace/_app/': typeof WorkspaceAppIndexRoute
  '/_platform/platform/': typeof PlatformPlatformIndexRoute
  '/$workspace/_app/contacts/$contactId': typeof WorkspaceAppContactsContactIdRoute
  '/$workspace/_app/contacts/new': typeof WorkspaceAppContactsNewRoute
  '/$workspace/_app/organizations/$organizationId': typeof WorkspaceAppOrganizationsOrganizationIdRoute
  '/$workspace/_app/organizations/new': typeof WorkspaceAppOrganizationsNewRoute
  '/$workspace/_app/reports/$reportKey': typeof WorkspaceAppReportsReportKeyRoute
  '/$workspace/_app/settings/agents': typeof WorkspaceAppSettingsAgentsRoute
  '/$workspace/_app/settings/api-clients': typeof WorkspaceAppSettingsApiClientsRoute
  '/$workspace/_app/settings/automation': typeof WorkspaceAppSettingsAutomationRoute
  '/$workspace/_app/settings/branding': typeof WorkspaceAppSettingsBrandingRoute
  '/$workspace/_app/settings/calendars': typeof WorkspaceAppSettingsCalendarsRoute
  '/$workspace/_app/settings/categories': typeof WorkspaceAppSettingsCategoriesRoute
  '/$workspace/_app/settings/general': typeof WorkspaceAppSettingsGeneralRoute
  '/$workspace/_app/settings/media': typeof WorkspaceAppSettingsMediaRoute
  '/$workspace/_app/settings/priority': typeof WorkspaceAppSettingsPriorityRoute
  '/$workspace/_app/settings/roles': typeof WorkspaceAppSettingsRolesRoute
  '/$workspace/_app/settings/shifts': typeof WorkspaceAppSettingsShiftsRoute
  '/$workspace/_app/settings/skills': typeof WorkspaceAppSettingsSkillsRoute
  '/$workspace/_app/settings/sla': typeof WorkspaceAppSettingsSlaRoute
  '/$workspace/_app/settings/teams': typeof WorkspaceAppSettingsTeamsRoute
  '/$workspace/_app/settings/tickets': typeof WorkspaceAppSettingsTicketsRoute
  '/$workspace/_app/settings/users': typeof WorkspaceAppSettingsUsersRoute
  '/$workspace/_app/tickets/$ticketId': typeof WorkspaceAppTicketsTicketIdRoute
  '/$workspace/_app/tickets/new': typeof WorkspaceAppTicketsNewRoute
  '/$workspace/_app/contacts/': typeof WorkspaceAppContactsIndexRoute
  '/$workspace/_app/organizations/': typeof WorkspaceAppOrganizationsIndexRoute
  '/$workspace/_app/reports/': typeof WorkspaceAppReportsIndexRoute
  '/$workspace/_app/settings/': typeof WorkspaceAppSettingsIndexRoute
  '/$workspace/_app/tickets/': typeof WorkspaceAppTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspace'
    | '/$workspace/notifications'
    | '/$workspace/settings'
    | '/$workspace/accept-invitation'
    | '/$workspace/login'
    | '/$workspace/reset-password'
    | '/platform/tenants'
    | '/$workspace/'
    | '/platform/'
    | '/$workspace/contacts/$contactId'
    | '/$workspace/contacts/new'
    | '/$workspace/organizations/$organizationId'
    | '/$workspace/organizations/new'
    | '/$workspace/reports/$reportKey'
    | '/$workspace/settings/agents'
    | '/$workspace/settings/api-clients'
    | '/$workspace/settings/automation'
    | '/$workspace/settings/branding'
    | '/$workspace/settings/calendars'
    | '/$workspace/settings/categories'
    | '/$workspace/settings/general'
    | '/$workspace/settings/media'
    | '/$workspace/settings/priority'
    | '/$workspace/settings/roles'
    | '/$workspace/settings/shifts'
    | '/$workspace/settings/skills'
    | '/$workspace/settings/sla'
    | '/$workspace/settings/teams'
    | '/$workspace/settings/tickets'
    | '/$workspace/settings/users'
    | '/$workspace/tickets/$ticketId'
    | '/$workspace/tickets/new'
    | '/$workspace/contacts/'
    | '/$workspace/organizations/'
    | '/$workspace/reports/'
    | '/$workspace/settings/'
    | '/$workspace/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspace'
    | '/$workspace/notifications'
    | '/$workspace/accept-invitation'
    | '/$workspace/login'
    | '/$workspace/reset-password'
    | '/platform/tenants'
    | '/platform'
    | '/$workspace/contacts/$contactId'
    | '/$workspace/contacts/new'
    | '/$workspace/organizations/$organizationId'
    | '/$workspace/organizations/new'
    | '/$workspace/reports/$reportKey'
    | '/$workspace/settings/agents'
    | '/$workspace/settings/api-clients'
    | '/$workspace/settings/automation'
    | '/$workspace/settings/branding'
    | '/$workspace/settings/calendars'
    | '/$workspace/settings/categories'
    | '/$workspace/settings/general'
    | '/$workspace/settings/media'
    | '/$workspace/settings/priority'
    | '/$workspace/settings/roles'
    | '/$workspace/settings/shifts'
    | '/$workspace/settings/skills'
    | '/$workspace/settings/sla'
    | '/$workspace/settings/teams'
    | '/$workspace/settings/tickets'
    | '/$workspace/settings/users'
    | '/$workspace/tickets/$ticketId'
    | '/$workspace/tickets/new'
    | '/$workspace/contacts'
    | '/$workspace/organizations'
    | '/$workspace/reports'
    | '/$workspace/settings'
    | '/$workspace/tickets'
  id:
    | '__root__'
    | '/'
    | '/$workspace'
    | '/_platform'
    | '/$workspace/_app'
    | '/$workspace/_auth'
    | '/$workspace/_app/notifications'
    | '/$workspace/_app/settings'
    | '/$workspace/_auth/accept-invitation'
    | '/$workspace/_auth/login'
    | '/$workspace/_auth/reset-password'
    | '/_platform/platform/tenants'
    | '/$workspace/_app/'
    | '/_platform/platform/'
    | '/$workspace/_app/contacts/$contactId'
    | '/$workspace/_app/contacts/new'
    | '/$workspace/_app/organizations/$organizationId'
    | '/$workspace/_app/organizations/new'
    | '/$workspace/_app/reports/$reportKey'
    | '/$workspace/_app/settings/agents'
    | '/$workspace/_app/settings/api-clients'
    | '/$workspace/_app/settings/automation'
    | '/$workspace/_app/settings/branding'
    | '/$workspace/_app/settings/calendars'
    | '/$workspace/_app/settings/categories'
    | '/$workspace/_app/settings/general'
    | '/$workspace/_app/settings/media'
    | '/$workspace/_app/settings/priority'
    | '/$workspace/_app/settings/roles'
    | '/$workspace/_app/settings/shifts'
    | '/$workspace/_app/settings/skills'
    | '/$workspace/_app/settings/sla'
    | '/$workspace/_app/settings/teams'
    | '/$workspace/_app/settings/tickets'
    | '/$workspace/_app/settings/users'
    | '/$workspace/_app/tickets/$ticketId'
    | '/$workspace/_app/tickets/new'
    | '/$workspace/_app/contacts/'
    | '/$workspace/_app/organizations/'
    | '/$workspace/_app/reports/'
    | '/$workspace/_app/settings/'
    | '/$workspace/_app/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace': {
      id: '/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/_app': {
      id: '/$workspace/_app'
      path: ''
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceAppRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/_auth': {
      id: '/$workspace/_auth'
      path: ''
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceAuthRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/_app/': {
      id: '/$workspace/_app/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof WorkspaceAppIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/notifications': {
      id: '/$workspace/_app/notifications'
      path: '/notifications'
      fullPath: '/$workspace/notifications'
      preLoaderRoute: typeof WorkspaceAppNotificationsRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/settings': {
      id: '/$workspace/_app/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof WorkspaceAppSettingsRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_auth/accept-invitation': {
      id: '/$workspace/_auth/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/$workspace/accept-invitation'
      preLoaderRoute: typeof WorkspaceAuthAcceptInvitationRouteImport
      parentRoute: typeof WorkspaceAuthRoute
    }
    '/$workspace/_auth/login': {
      id: '/$workspace/_auth/login'
      path: '/login'
      fullPath: '/$workspace/login'
      preLoaderRoute: typeof WorkspaceAuthLoginRouteImport
      parentRoute: typeof WorkspaceAuthRoute
    }
    '/$workspace/_auth/reset-password': {
      id: '/$workspace/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/$workspace/reset-password'
      preLoaderRoute: typeof WorkspaceAuthResetPasswordRouteImport
      parentRoute: typeof WorkspaceAuthRoute
    }
    '/_platform/platform/': {
      id: '/_platform/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformPlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/platform/tenants': {
      id: '/_platform/platform/tenants'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformPlatformTenantsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/$workspace/_app/contacts/': {
      id: '/$workspace/_app/contacts/'
      path: '/contacts'
      fullPath: '/$workspace/contacts/'
      preLoaderRoute: typeof WorkspaceAppContactsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/contacts/$contactId': {
      id: '/$workspace/_app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/$workspace/contacts/$contactId'
      preLoaderRoute: typeof WorkspaceAppContactsContactIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/contacts/new': {
      id: '/$workspace/_app/contacts/new'
      path: '/contacts/new'
      fullPath: '/$workspace/contacts/new'
      preLoaderRoute: typeof WorkspaceAppContactsNewRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/organizations/': {
      id: '/$workspace/_app/organizations/'
      path: '/organizations'
      fullPath: '/$workspace/organizations/'
      preLoaderRoute: typeof WorkspaceAppOrganizationsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/organizations/$organizationId': {
      id: '/$workspace/_app/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/$workspace/organizations/$organizationId'
      preLoaderRoute: typeof WorkspaceAppOrganizationsOrganizationIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/organizations/new': {
      id: '/$workspace/_app/organizations/new'
      path: '/organizations/new'
      fullPath: '/$workspace/organizations/new'
      preLoaderRoute: typeof WorkspaceAppOrganizationsNewRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/reports/': {
      id: '/$workspace/_app/reports/'
      path: '/reports'
      fullPath: '/$workspace/reports/'
      preLoaderRoute: typeof WorkspaceAppReportsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/reports/$reportKey': {
      id: '/$workspace/_app/reports/$reportKey'
      path: '/reports/$reportKey'
      fullPath: '/$workspace/reports/$reportKey'
      preLoaderRoute: typeof WorkspaceAppReportsReportKeyRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/settings/': {
      id: '/$workspace/_app/settings/'
      path: '/'
      fullPath: '/$workspace/settings/'
      preLoaderRoute: typeof WorkspaceAppSettingsIndexRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/agents': {
      id: '/$workspace/_app/settings/agents'
      path: '/agents'
      fullPath: '/$workspace/settings/agents'
      preLoaderRoute: typeof WorkspaceAppSettingsAgentsRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/api-clients': {
      id: '/$workspace/_app/settings/api-clients'
      path: '/api-clients'
      fullPath: '/$workspace/settings/api-clients'
      preLoaderRoute: typeof WorkspaceAppSettingsApiClientsRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/automation': {
      id: '/$workspace/_app/settings/automation'
      path: '/automation'
      fullPath: '/$workspace/settings/automation'
      preLoaderRoute: typeof WorkspaceAppSettingsAutomationRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/branding': {
      id: '/$workspace/_app/settings/branding'
      path: '/branding'
      fullPath: '/$workspace/settings/branding'
      preLoaderRoute: typeof WorkspaceAppSettingsBrandingRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/calendars': {
      id: '/$workspace/_app/settings/calendars'
      path: '/calendars'
      fullPath: '/$workspace/settings/calendars'
      preLoaderRoute: typeof WorkspaceAppSettingsCalendarsRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/categories': {
      id: '/$workspace/_app/settings/categories'
      path: '/categories'
      fullPath: '/$workspace/settings/categories'
      preLoaderRoute: typeof WorkspaceAppSettingsCategoriesRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/general': {
      id: '/$workspace/_app/settings/general'
      path: '/general'
      fullPath: '/$workspace/settings/general'
      preLoaderRoute: typeof WorkspaceAppSettingsGeneralRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/media': {
      id: '/$workspace/_app/settings/media'
      path: '/media'
      fullPath: '/$workspace/settings/media'
      preLoaderRoute: typeof WorkspaceAppSettingsMediaRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/priority': {
      id: '/$workspace/_app/settings/priority'
      path: '/priority'
      fullPath: '/$workspace/settings/priority'
      preLoaderRoute: typeof WorkspaceAppSettingsPriorityRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/roles': {
      id: '/$workspace/_app/settings/roles'
      path: '/roles'
      fullPath: '/$workspace/settings/roles'
      preLoaderRoute: typeof WorkspaceAppSettingsRolesRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/shifts': {
      id: '/$workspace/_app/settings/shifts'
      path: '/shifts'
      fullPath: '/$workspace/settings/shifts'
      preLoaderRoute: typeof WorkspaceAppSettingsShiftsRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/skills': {
      id: '/$workspace/_app/settings/skills'
      path: '/skills'
      fullPath: '/$workspace/settings/skills'
      preLoaderRoute: typeof WorkspaceAppSettingsSkillsRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/sla': {
      id: '/$workspace/_app/settings/sla'
      path: '/sla'
      fullPath: '/$workspace/settings/sla'
      preLoaderRoute: typeof WorkspaceAppSettingsSlaRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/teams': {
      id: '/$workspace/_app/settings/teams'
      path: '/teams'
      fullPath: '/$workspace/settings/teams'
      preLoaderRoute: typeof WorkspaceAppSettingsTeamsRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/tickets': {
      id: '/$workspace/_app/settings/tickets'
      path: '/tickets'
      fullPath: '/$workspace/settings/tickets'
      preLoaderRoute: typeof WorkspaceAppSettingsTicketsRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/settings/users': {
      id: '/$workspace/_app/settings/users'
      path: '/users'
      fullPath: '/$workspace/settings/users'
      preLoaderRoute: typeof WorkspaceAppSettingsUsersRouteImport
      parentRoute: typeof WorkspaceAppSettingsRoute
    }
    '/$workspace/_app/tickets/': {
      id: '/$workspace/_app/tickets/'
      path: '/tickets'
      fullPath: '/$workspace/tickets/'
      preLoaderRoute: typeof WorkspaceAppTicketsIndexRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/tickets/$ticketId': {
      id: '/$workspace/_app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/$workspace/tickets/$ticketId'
      preLoaderRoute: typeof WorkspaceAppTicketsTicketIdRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
    '/$workspace/_app/tickets/new': {
      id: '/$workspace/_app/tickets/new'
      path: '/tickets/new'
      fullPath: '/$workspace/tickets/new'
      preLoaderRoute: typeof WorkspaceAppTicketsNewRouteImport
      parentRoute: typeof WorkspaceAppRoute
    }
  }
}

interface WorkspaceAppSettingsRouteChildren {
  WorkspaceAppSettingsAgentsRoute: typeof WorkspaceAppSettingsAgentsRoute
  WorkspaceAppSettingsApiClientsRoute: typeof WorkspaceAppSettingsApiClientsRoute
  WorkspaceAppSettingsAutomationRoute: typeof WorkspaceAppSettingsAutomationRoute
  WorkspaceAppSettingsBrandingRoute: typeof WorkspaceAppSettingsBrandingRoute
  WorkspaceAppSettingsCalendarsRoute: typeof WorkspaceAppSettingsCalendarsRoute
  WorkspaceAppSettingsCategoriesRoute: typeof WorkspaceAppSettingsCategoriesRoute
  WorkspaceAppSettingsGeneralRoute: typeof WorkspaceAppSettingsGeneralRoute
  WorkspaceAppSettingsMediaRoute: typeof WorkspaceAppSettingsMediaRoute
  WorkspaceAppSettingsPriorityRoute: typeof WorkspaceAppSettingsPriorityRoute
  WorkspaceAppSettingsRolesRoute: typeof WorkspaceAppSettingsRolesRoute
  WorkspaceAppSettingsShiftsRoute: typeof WorkspaceAppSettingsShiftsRoute
  WorkspaceAppSettingsSkillsRoute: typeof WorkspaceAppSettingsSkillsRoute
  WorkspaceAppSettingsSlaRoute: typeof WorkspaceAppSettingsSlaRoute
  WorkspaceAppSettingsTeamsRoute: typeof WorkspaceAppSettingsTeamsRoute
  WorkspaceAppSettingsTicketsRoute: typeof WorkspaceAppSettingsTicketsRoute
  WorkspaceAppSettingsUsersRoute: typeof WorkspaceAppSettingsUsersRoute
  WorkspaceAppSettingsIndexRoute: typeof WorkspaceAppSettingsIndexRoute
}

const WorkspaceAppSettingsRouteChildren: WorkspaceAppSettingsRouteChildren = {
  WorkspaceAppSettingsAgentsRoute: WorkspaceAppSettingsAgentsRoute,
  WorkspaceAppSettingsApiClientsRoute: WorkspaceAppSettingsApiClientsRoute,
  WorkspaceAppSettingsAutomationRoute: WorkspaceAppSettingsAutomationRoute,
  WorkspaceAppSettingsBrandingRoute: WorkspaceAppSettingsBrandingRoute,
  WorkspaceAppSettingsCalendarsRoute: WorkspaceAppSettingsCalendarsRoute,
  WorkspaceAppSettingsCategoriesRoute: WorkspaceAppSettingsCategoriesRoute,
  WorkspaceAppSettingsGeneralRoute: WorkspaceAppSettingsGeneralRoute,
  WorkspaceAppSettingsMediaRoute: WorkspaceAppSettingsMediaRoute,
  WorkspaceAppSettingsPriorityRoute: WorkspaceAppSettingsPriorityRoute,
  WorkspaceAppSettingsRolesRoute: WorkspaceAppSettingsRolesRoute,
  WorkspaceAppSettingsShiftsRoute: WorkspaceAppSettingsShiftsRoute,
  WorkspaceAppSettingsSkillsRoute: WorkspaceAppSettingsSkillsRoute,
  WorkspaceAppSettingsSlaRoute: WorkspaceAppSettingsSlaRoute,
  WorkspaceAppSettingsTeamsRoute: WorkspaceAppSettingsTeamsRoute,
  WorkspaceAppSettingsTicketsRoute: WorkspaceAppSettingsTicketsRoute,
  WorkspaceAppSettingsUsersRoute: WorkspaceAppSettingsUsersRoute,
  WorkspaceAppSettingsIndexRoute: WorkspaceAppSettingsIndexRoute,
}

const WorkspaceAppSettingsRouteWithChildren =
  WorkspaceAppSettingsRoute._addFileChildren(WorkspaceAppSettingsRouteChildren)

interface WorkspaceAppRouteChildren {
  WorkspaceAppNotificationsRoute: typeof WorkspaceAppNotificationsRoute
  WorkspaceAppSettingsRoute: typeof WorkspaceAppSettingsRouteWithChildren
  WorkspaceAppIndexRoute: typeof WorkspaceAppIndexRoute
  WorkspaceAppContactsContactIdRoute: typeof WorkspaceAppContactsContactIdRoute
  WorkspaceAppContactsNewRoute: typeof WorkspaceAppContactsNewRoute
  WorkspaceAppOrganizationsOrganizationIdRoute: typeof WorkspaceAppOrganizationsOrganizationIdRoute
  WorkspaceAppOrganizationsNewRoute: typeof WorkspaceAppOrganizationsNewRoute
  WorkspaceAppReportsReportKeyRoute: typeof WorkspaceAppReportsReportKeyRoute
  WorkspaceAppTicketsTicketIdRoute: typeof WorkspaceAppTicketsTicketIdRoute
  WorkspaceAppTicketsNewRoute: typeof WorkspaceAppTicketsNewRoute
  WorkspaceAppContactsIndexRoute: typeof WorkspaceAppContactsIndexRoute
  WorkspaceAppOrganizationsIndexRoute: typeof WorkspaceAppOrganizationsIndexRoute
  WorkspaceAppReportsIndexRoute: typeof WorkspaceAppReportsIndexRoute
  WorkspaceAppTicketsIndexRoute: typeof WorkspaceAppTicketsIndexRoute
}

const WorkspaceAppRouteChildren: WorkspaceAppRouteChildren = {
  WorkspaceAppNotificationsRoute: WorkspaceAppNotificationsRoute,
  WorkspaceAppSettingsRoute: WorkspaceAppSettingsRouteWithChildren,
  WorkspaceAppIndexRoute: WorkspaceAppIndexRoute,
  WorkspaceAppContactsContactIdRoute: WorkspaceAppContactsContactIdRoute,
  WorkspaceAppContactsNewRoute: WorkspaceAppContactsNewRoute,
  WorkspaceAppOrganizationsOrganizationIdRoute:
    WorkspaceAppOrganizationsOrganizationIdRoute,
  WorkspaceAppOrganizationsNewRoute: WorkspaceAppOrganizationsNewRoute,
  WorkspaceAppReportsReportKeyRoute: WorkspaceAppReportsReportKeyRoute,
  WorkspaceAppTicketsTicketIdRoute: WorkspaceAppTicketsTicketIdRoute,
  WorkspaceAppTicketsNewRoute: WorkspaceAppTicketsNewRoute,
  WorkspaceAppContactsIndexRoute: WorkspaceAppContactsIndexRoute,
  WorkspaceAppOrganizationsIndexRoute: WorkspaceAppOrganizationsIndexRoute,
  WorkspaceAppReportsIndexRoute: WorkspaceAppReportsIndexRoute,
  WorkspaceAppTicketsIndexRoute: WorkspaceAppTicketsIndexRoute,
}

const WorkspaceAppRouteWithChildren = WorkspaceAppRoute._addFileChildren(
  WorkspaceAppRouteChildren,
)

interface WorkspaceAuthRouteChildren {
  WorkspaceAuthAcceptInvitationRoute: typeof WorkspaceAuthAcceptInvitationRoute
  WorkspaceAuthLoginRoute: typeof WorkspaceAuthLoginRoute
  WorkspaceAuthResetPasswordRoute: typeof WorkspaceAuthResetPasswordRoute
}

const WorkspaceAuthRouteChildren: WorkspaceAuthRouteChildren = {
  WorkspaceAuthAcceptInvitationRoute: WorkspaceAuthAcceptInvitationRoute,
  WorkspaceAuthLoginRoute: WorkspaceAuthLoginRoute,
  WorkspaceAuthResetPasswordRoute: WorkspaceAuthResetPasswordRoute,
}

const WorkspaceAuthRouteWithChildren = WorkspaceAuthRoute._addFileChildren(
  WorkspaceAuthRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceAppRoute: typeof WorkspaceAppRouteWithChildren
  WorkspaceAuthRoute: typeof WorkspaceAuthRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAppRoute: WorkspaceAppRouteWithChildren,
  WorkspaceAuthRoute: WorkspaceAuthRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface PlatformRouteChildren {
  PlatformPlatformTenantsRoute: typeof PlatformPlatformTenantsRoute
  PlatformPlatformIndexRoute: typeof PlatformPlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformPlatformTenantsRoute: PlatformPlatformTenantsRoute,
  PlatformPlatformIndexRoute: PlatformPlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
